GoogleChromeLabs/ps-analysis-tool

- .github/workflows/tests-unit-js.yml
- README.md
- package.json
- packages/cli/package.json
- packages/extension/package.json
- packages/extension/src/localStore/tests/cookieStore.ts
- packages/extension/src/localStore/tests/updateStorage.ts
- packages/extension/src/view/devtools/components/tabSelector.tsx
- packages/extension/src/view/devtools/components/tabs/CookieTab/cookieList.tsx
- packages/extension/src/view/devtools/components/tabs/CookieTab/index.tsx
- packages/extension/src/view/devtools/components/tests/tabSelecter.tsx
- packages/extension/src/view/devtools/index.html
- packages/extension/tailwind.config.cjs
- packages/extension/tsconfig.json
- tsconfig.shared.json
- webpack.config.cjs
Add GitHub Workflow for running tests and following other small fixes.
1. Try updated command
`npm run dev`
`npm run build`
2. Open devtools's  devtool, there should be no `index.css` file not found warning.
3. Run `npm run lint` to test if test folders type checking happens.
4. Check if "Javascript Unit Test" job is running and passing
> Add GitHub Workflow for running tests

- package-lock.json
- packages/extension/package.json
- packages/extension/src/utils/isFirstParty.ts
- packages/extension/src/utils/parseUrl.ts
- packages/extension/src/utils/tests/isFirstParty.ts
- packages/extension/src/view/devtools/components/tabs/CookieTab/listItem.tsx
- packages/extension/src/view/devtools/devtools.html
Since we consider subdomains as first-party, it crucial to accurately determine whether a URL is a subdomain of the provided URL
Subdomains can have various formats and can be nested to multiple levels. Additionally, different domain name patterns and top-level domains (TLDs) can introduce further complexity.
While a basic regular expression pattern could capture subdomains in simple cases, it may not cover all possible scenarios. It would not account for variations such as internationalized domain names (IDNs), complex TLDs, subdomains with hyphens, or subdomains with different levels.
**Example:**
Internationalized Domain Names (IDNs):
URL: https://日本.example.com
Subdomain: 日本
Complex TLDs:
URL: https://example.co.uk
Subdomain: Empty (no subdomain)
Subdomains with Hyphens:
URL: …
> Implement the tldts package for identifying first and third-party domains.

- packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
- packages/extension/src/worker/service-worker.ts
Changes in cookie store caused by some websites cause overload on stateProvider in devtools. This PR removes the listener for the same from service worker and stateProvider in devtools.
---
Fixes #
> Fix: infinite render on some websites.

- packages/extension/src/view/devtools/components/tabContent/cookies/cookiesListing/cookieTable/index.tsx
This PR changes the table's sorting function from `alphanumericCaseSensitive` to `basic`.
React table sorting functions reference - [here](https://tanstack.com/table/v8/docs/api/features/sorting#sorting-functions)
---
Fixes #
> Update table's column sorting function

- packages/extension/src/view/devtools/components/tabContent/cookies/cookiesLanding/cookiesMatrix/index.tsx
- packages/extension/src/view/devtools/stateProviders/filterManagementStore/constants.ts
- packages/extension/src/view/devtools/stateProviders/filterManagementStore/types.ts
- packages/extension/src/view/devtools/stateProviders/filterManagementStore/utils/getFilters.ts
This PR aims to add the capability to change the order of the filter items in the filter UI.
> Add functionality to change order of filters.

- package-lock.json
- packages/extension/src/view/design-system/components/circlePieChart/index.tsx
- packages/extension/src/view/devtools/components/tabContent/cookies/cookiesLanding/cookiesMatrix/index.tsx
This PR includes code to move info icon from matrix's `Circle` to `Cookie Matrix` in Landing page.
---
Fixes #
> Relocate info icon from matrix to cookie insights on landing page

- packages/extension/src/view/devtools/components/tabContent/cookies/cookiesListing/cookieTable/index.tsx
- packages/extension/src/view/devtools/components/tabContent/cookies/cookiesListing/index.tsx
- packages/extension/src/view/devtools/components/tabContent/cookies/tests/cookieTab.tsx
- packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
This PR contains code to debounce enable and disabling of table sorting. When user moves his cursor inside the header, the sorting enables and as he leaves the sorting gets disabled with debounce to both actions.
---
Fixes #
> Debounce the toggling functionality of table sorting

- README.md
- packages/cli/src/index.ts
- packages/cli/src/types.ts
- packages/cli/src/utils/generatePrefix.ts
- packages/cli/src/utils/generateTechnology.ts
The dependency `Wappalyzer` which is used for tech stack analysis of any website asks for permission to run its unsigned copy of chromium on some systems. This PR adds a flag to skip the tech stack analysis step so that any users finding the dialog box annoying may skip the step (specially during a sitemap analysis).
- Build the cli as mentioned in the README.MD.
- Use the cli as mentioned in the README.MD but with `-nt` flag.
- E.g. `npm run cli -- -s https://example.com/sitemap_index.xml -nt`
---
Fixes #
> Feature: Optional tech analysis

- package-lock.json
- packages/cli/package.json
As per the [dependable bot](https://github.com/GoogleChromeLabs/ps-analysis-tool/security/dependabot/8)
xml2js versions before 0.5.0 allows an external attacker to edit or add new properties to an object. This is possible because the application does not properly validate incoming JSON keys, thus allowing the __proto__ property to be edited.
Downgrade sitemapper package because the latest version depends on vulnerable versions of xml2js
---
Fixes #
> Downgrade sitemapper package.

- package-lock.json
- package.json
[Previous PR](https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/144) couldn't fix the vulnerabilities (ran `npm audit fix`) issue, therefore we override the xml2js version.
---
Fixes #
> Override xml2js dependency to fix vulnerabilities

- packages/design-system/src/components/table/useColumnResizing/index.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/cookieTable/index.tsx
This PR aims to fix the issue of the table not taking up the whole space when the DecTools dock type is changed.
- Table is forced rerendered once the dock type is changed.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/59614577/8a3ca298-b493-4782-8a36-9e4be9f52492
> Fix: Responsive table on changing dock size.

- packages/extension/src/contentScript/index.ts
When we open devtool or resize the devtool, we often see the following error. This PR fixes that issue.
---
Fixes #
> Fix browseTopics pre-rendering error

- packages/design-system/src/components/bulletList/index.tsx
- packages/design-system/src/components/bulletList/listRow.tsx
- packages/design-system/src/components/landingPage/index.tsx
- packages/design-system/src/icons/arrow-up.svg
- packages/extension/src/view/design-system/components/infoCard/index.tsx
- packages/extension/src/view/design-system/components/infoCard/learnMoreDropdown.tsx
- packages/extension/src/view/design-system/components/infoCard/tests/infoCard.test.tsx
- packages/extension/src/view/devtools/components/antiCovertTracking/antiCovertTracking.tsx
- packages/extension/src/view/devtools/components/antiCovertTracking/bounceTracking/index.tsx
- packages/extension/src/view/devtools/components/antiCovertTracking/fingerprinting/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/attribution/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/privateAdvertising.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/topics/index.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/chips/index.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/index.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/siteBoundaries.tsx
- packages/extension/src/view/devtools/tests/app.tsx
This PR updates the landing page to encompass some enhancements and fixes some QA issues
- By default, when a page is loaded, the dropdown is in collapsed state. On user toggling, it shows up the content.
- In case of "CHIPS" or "Topics" or "Attribution", "Bounce Tracking", "Fingerprinting", page is wrapped in LandingPage component to display collapsible content.
- The InfoCard component is rendered in two variants - one with header (having border, separator in case of "Related Website Sets") and other as plain text (in case it's being rendered in collapsible page for example- CHIPS, Topics etc). So, a prop hasHeader is introduced to differentiate.
- WIP components has been removed
- Responsiveness and theme issues highlighted in QA has been addressed
---
Fixes #
> Landing page enhancements and fixes

- .github/ISSUE_TEMPLATE/third-party-cookie-breakage-report.md
Adding a new issue template so that it can be mentioned in the `Quick Links` sections of our landing pages and make it easier for the user to report a breakage for us to review while they test their site using our tool.
> Create third-party-cookie-breakage-report issue template

- packages/design-system/src/components/landingPage/index.tsx
- packages/extension/src/contentScript/index.ts
- packages/extension/src/contentScript/types.ts
- packages/extension/src/view/devtools/hooks/useFrameOverlay.ts
- packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
It was noticed that overlay on an iframe with an empty origin would flicker. This PR aims to solve that issue.
- Add another state to detect whether the frame was selected from DevTools or from hovering of mouse while inspecting an iframe on the page.
> Fix: Flickering of iframe overlay on sites and some other fixes

- packages/cli/src/procedures/analyzeTechnologiesUrlsInBatches.ts
- packages/cli/src/utils/browserManagement/index.ts
This PR fixes a bug found while smoke testing. Due to a missing filtration step in "responseReceivedExtraInfo" blocked cookies where counted as accepted cookies which misattributed some 3p cookies to be marked as not affected when they are.
The missing filtration step is added in this PR.
---
Fixes #
> Fix: Misattribution of affected cookies

- packages/extension/src/contentScript/index.ts
- packages/extension/src/utils/test-data/globalChrome.ts
- packages/extension/src/view/devtools/components/sidebar/index.tsx
- packages/extension/src/view/devtools/components/sidebar/keyboardNavigationHandlers/arrowDownHandler.ts
- packages/extension/src/view/devtools/components/sidebar/keyboardNavigationHandlers/arrowUpHandler.ts
- packages/extension/src/view/devtools/hooks/useFrameOverlay.ts
- packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
- packages/extension/src/view/devtools/tests/app.tsx
- packages/extension/src/view/devtools/tests/index.tsx
This PR aims to fix the issues of scrolling into view functionality of the frame overlay feature.
- Send a message from the content script to the extension once the content script is initialised on the webpage. Once the content-script is initialised in the webpage the inspect button will be shown.
- Modify scrollIntoView values to fix the scrolling issue of the webpage.
> Fix: Frame overlay issues of scrolling into view

- packages/extension/src/view/devtools/stateProviders/filterManagementStore/constants.ts
This PR aims to introduce a hotfix for the bug where `SameSite` filter showed undefined in filter chips in `cookieTopBar`.
- Add `sameSite` constant to `MAPPING_KEYS_TO_NAME`.
- Open this branch in a terminal.
- Run `npm start`.
- Open `aljazeera.com` in Chrome. Open DevTools and go to `PrivacySandbox` Tab in DevTools.
- Click on the arrow which is on the left `Cookies` header.
- Go to any frame and select filter you should see the filters in a new way `FilterName: selectedFilterValue`
---
> Fix: SameSite showing undefined in chips

- packages/cli-dashboard/src/components/utils/reportDownloader.ts
- packages/extension/src/utils/getCurrentTabId.ts
This PR aims to club all the same name cookies that are in different frames before writing them to the CSV document.
---
> Fix: Report downloader duplicate cookie entries in CSV

- packages/extension/src/contentScript/index.ts
- packages/extension/src/contentScript/popovers/tooltip/setTooltipPosition.ts
This PR aims to solve tooltip calculation problems and adds a capability to calculate the tooltip and overlay position on window resize.
- Calculate tooltip positions by checking left, right, top and bottom spacing.
- Add a callback to calculate the position on resize.
- Change parameters for scrollIntoView to have proper scrolling behaviour.
---
> Fix: Frame overlay issues

- packages/cli-dashboard/src/app.tsx
- packages/cli/src/index.ts
- packages/cli/src/utils/checkPortInUse.ts
- Error message improvements.
- Message text updated to: Error: Report server port (9000) already in use. You might be already running CLI.
- Process exits after throwing error.
- Port usage is tested before starting analysis.
- Out out Url changes
- Cli and Cli dashboard are updated to use the just the folder name in the URL search params.
---
Fixes #
> Fix: CLI std output changes

- packages/extension/src/contentScript/popovers/tooltip/setTooltipPosition.ts
This PR aims to solve tooltip calculation problems and adds a capability to calculate the tooltip and overlay position on window resize.
- Calculate tooltip positions by checking left, right, top and bottom spacing.
- Add a callback to calculate the position on resize.
- Change parameters for scrollIntoView to have proper scrolling behaviour.
---
> Fix: Frame overlay tooltip calculation issue

- packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesListing/cookieTableContainer/index.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/cookieTableContainer/index.tsx
Adds cross icon in the cookie accepted column rather than leaving it empty for false values.
---
Fixes #
> Enhancement: Add cross icon to cookie accepted column

- data/PSInfo.json
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/jsonOutput/otherDomainOutput.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/jsonOutput/primaryDomainOutput.tsx
This PR updates the submission steps for `RWS` submission after JSON data generation and `.well-known` URL path.
---
Fixes #224
> Update `RWS` submission steps text

- packages/extension/src/contentScript/index.ts
Fix the following opaque origin error when using `document.browsingTopics`
> Uncaught (in promise) InvalidAccessError: document.browsingTopics() is not allowed in an opaque origin context.
>
---
Fixes #
> Handle opaque origin error when using `document.browsingTopics`

- packages/extension/src/view/devtools/components/cookies/cookieFilter/index.tsx
- packages/extension/src/view/devtools/components/cookies/cookieFilter/subList.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/index.tsx
This PR fixes the squeezing of the checkbox in the dark theme when the parent component is resized alongside the unavailability of a resizer when filters overflow the container.
---
Fixes #
> Fix: Update checkbox dimensions and resizer visiblity

- packages/extension/src/localStore/cookieStore.ts
- packages/extension/src/serviceWorker/createCookieObject.ts
This PR aims to remove duplicate cookies from the cookie table which were induced because of whitespace in parsed cookies.
- Add `.trim` function after getting cookie key.
- As a fallback trim whitespace from name, domain and path while parsing cookie key in request and response.
---
> Fix: Trim out whitespace from the cookie key.

- packages/cli/src/procedures/analyzeTechnologiesUrlsInBatches.ts
Fixes `MaxListenerExceedWarning` warning thrown when analyzing technology for sitemaps. 
`Wappalyzer` doesn't automatically cleanup after doing analysis. `destroy` function must be called before starting new batch of analysis.
Fixes #258
> Fix: MaxListenerExceedWarning when analyzing sitemap

- packages/cli/src/index.ts
- packages/cli/src/procedures/analyzeCookieUrlsInBatches.ts
- packages/cli/src/procedures/analyzeTechnologiesUrlsInBatches.ts
- packages/common/src/index.ts
CLI accepts CSV file as an argument with. The list of URLs provided through the file will be then used for further analysis.
- Follow instructions in the README.MD to build CLI.
- Use the new `-c` or `--csv-path` argument to pass a local csv file.
`npm run cli -- -c /path/to/urlset.csv`
---
Fixes #220
> Enhancement: add interface use CSV file in CLI.

- packages/cli-dashboard/src/components/utils/reportDownloader.ts
- packages/cli-dashboard/src/types.ts
- packages/common/src/index.ts
- packages/common/src/utils/sanitizeCsvRecord.ts
- packages/common/src/utils/tests/sanitizeCsvRecords.ts
- packages/common/tsconfig.json
It was observed (in issue #284) that in the exported reports in the CSV files the values of the column `Cookie Affected` was flipped. This PR fixes the wrong value serialization and removes the column `Cookie Affected` from the `affected-cookies.csv` file due to it being redundant since all cookies listed in that file are affected. 
- Added a utility function in `./packages/common/src/utils/sanitizeCsvRecord.ts` for converting a string into a valid CSV record according to [RFC](https://datatracker.ietf.org/doc/html/rfc4180). 
Fixes #284
> Fix: Affected cookies csv output

- packages/extension/src/view/devtools/components/cookies/cookiesListing/index.tsx
This PR updates the filter function for "set via" filtering. This solves the bug when choosing both options filters out all cookies in the list.
> Fix: Update filtering function

- packages/common/src/utils/filterCookiesByFrame.ts
- packages/extension/src/view/devtools/hooks/useFrameOverlay.ts
- packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
Sometimes frames could be added and removed resulting in the cookies set by those frames to disappear from the application tab and show up in the network tab along with the PSAT tab. To fix this we have added an `Unknown frame(s)` which will show the collection of all such cookies present in the extension.
Partially addresses #339
> Fix: Add unknown frames in extension.

- packages/extension/src/utils/setDocumentCookies.ts
The cookies which were set by javascript, when being collected did not join the `=` in the cookie value thus adding a discrepancy in the value being shown in the table.
---
Partially addresses #301
> Fix the method of fetching value for JS cookies.

- packages/design-system/src/utils/prepareFrameStatsComponent.ts
On the Cookies landing page in the Frame details section, the count for frames doesn't have a plural version for the frames counting.  This pull request includes a plural version for counting frames when the amount is greater than one. 
This pull request adds a conditional to `prepareFrameStatsComponent` to display the plural string "Frames".
**before:**
**after:**
---
Fixes #
> Adding plural string for "Frame details" sections

- bin/install.sh
Adds missing documentation for launcher command help text after installation, that was to be a part of https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/211
> Enhancement: Add additional documentation with Chrome launcher commands

- packages/design-system/src/components/table/components/tableBody/bodyCell.tsx
- packages/design-system/src/components/table/components/tableBody/index.tsx
Enable `Ctrl+C` or `Command+C(MAC)` on the cookie listing table, so the user can copy the cookie name by keyboard's shortcut only not by right-clicking and copying.
- On double-click select the entire cell content and the copy command copies the selected text.
- Stop propagation of key down event from table cell if copy commands keys are pressed.
1. Clone the `feat/copy-paste-keyboard` branch and run `npm run build` in local.
2. Refresh or reupload this extension in your Chrome as per the instructions available in the [README](https://github.com/rtCamp/cookie-analysis-tool-internal#extension-from-source).
3. Open the dev tool and check if the user can able to copy the cookie name from the cookie's table.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/59614577/57fc7d04-7d52-4b7 …
> Feature: Copy paste using keyboard

- packages/common/src/utils/tests/findAnalyticsMatch.ts
While resolving issue #424 a unit test was added to the utility `findAnalyticsMatch` testing its capability to match with postfix and prefix wildcard entries in CokieDB. It was realized that it was capable of matching for prefix wildcard entries if they were in CookieDB.
This PR adds the above-mentioned test to the 'develop' branch.
Fixes #424
> Chore: Add unit test for findAnalyticsMatch

- packages/cli/src/index.ts
Fix for CLI dashboard not visualizing data. In the CLI routine, there was a minor bug that caused the `out.json` to be in the wrong directory.
> Fix: CLI dashboard not showing data

- packages/cli/src/index.ts
- packages/cli/src/utils/validateArgs.ts
There are a few typos on the Default and Help message from the CLI. This pull request is related to issue #450
- run the CLI without any option ´npm run cli´
- run the help command from CLI ´npm run cli -- --help´
---
Fixes #
> Updating CLI default and help message

- packages/extension/src/serviceWorker/index.ts
- packages/extension/src/view/devtools/components/cookies/cookiesListing/rowContextMenu.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/isCookieDomainInAllowList.ts
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/setParentDomain.ts
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/useHighlighting.tsx
- packages/extension/src/view/devtools/components/cookies/tests/rowContextMenu.tsx
- In the allow list feature, an added allowed domain is stored in `chrome.contentSettings` for the current browser session. However, this created an issue when the user creates multiple windows while using PSAT, as the content setting gets cleared each time a new chrome window is opened.
- Fix parent domain issue reported by QA
- Update context menu text from "Add Domain to Allow List" to "Allow Domain During Session"
- Count number of windows before clearing content  to ensure that we do not clear it on new window open.
- Do not clear content settings on install
---
Related #376
> Fix miscellaneous allow list QA issues

- packages/extension/src/view/devtools/app.tsx
In a multi-tab environment, it was noticed that when the extension is updated or refreshed the count resets to zero and will only increase once any network request with a cookie is processed. On a static site, the count stays at 0 because it doesn't send or receive so the count will stay 0 indefinitely.
- Clone this branch. In the terminal `npm start`.
- Go to any page and open PSAT to enable `multi-tab` debugging.
- Now on the extensions page refresh the extension.
- On the page with PSAT. Click on the refresh panel once it appears you should see the page being refreshed.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/59614577/c642b61f-8d0b-4186-b2b9-321482f76a44
---
Fixes #462
> Fix: Refresh page on context invalidate

- packages/extension/src/serviceWorker/index.ts
- packages/extension/src/store/synchnorousCookieStore.ts
- packages/extension/src/store/tests/synchnorousCookieStore.ts
- packages/extension/src/store/utils/updateCookieBadgeText.ts
- packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
This PR solves the errors which are not breaking but are making a problem while debugging the extension for any breakages.
---
Partially addressed #471
> Fix: Errors appearing on extension page.

- packages/extension/src/serviceWorker/index.ts
This PR aims to solve the 0 cookie issue by calling the chrome.storage.local.get after every 28 seconds, so that the service worker doesn't idle and sleep.
Choices were made after reading the following doc.
https://developer.chrome.com/blog/longer-esw-lifetimes#whats_changed
---
Partially addresses #471
> HotFix: Persist data using global variable

- packages/library-detection/src/core/stateProvider/index.tsx
We've encountered an issue with the loader on the cookie landing screen's "known breakages" section, where it fails to deactivate under specific circumstances.
The root cause was identified as a conditional check for the active tab status before executing the loader's deactivation logic. If the tab being monitored transitions from a loading to a completed state while the user is focused on another tab, the loader remains active, and the intended detection logic does not execute. To address this, we've removed the active tab check, allowing the deactivation logic to run irrespective of tab focus.
To replicate the issue, follow these steps:
1. Open two browser tabs.
2. Navigate to [example.com](https://example.com) on Tab 1 and access the PSAT extension's cookie landing page.
3. Open …
> Fix: Library detection section occasional infinite loading

- packages/extension/src/manifest.json
- packages/extension/src/store/synchnorousCookieStore.ts
This PR fixes the cookie count on page reload and removes the `unlimitedStoage` permission from `manifest.json`.
---
> Fix: Slow loading cookies on page change

- bin/chrome_launcher.sh
Disables **auto-opening** of Chrome DevTools by default for all tabs
> [Main] Disable auto opening of Chrome DevTools by default for all tabs

- packages/cli-dashboard/src/components/siteReport/tabs/technologies/index.tsx
Add a "No description available" text in technology table. 
Partially Addresses #471
> Fix: add conditional rendering in technology details panel

- packages/common/src/index.ts
- packages/common/src/utils/extractUrl.ts
- packages/library-detection/src/components/libraryDetection/index.tsx
- packages/library-detection/src/config.ts
- packages/library-detection/src/core/filterMatchesBasedOnExceptions.ts
- packages/library-detection/src/core/hooks/useLibraryDetection.ts
- packages/library-detection/src/core/index.ts
- packages/library-detection/src/core/stateProvider/index.tsx
- packages/library-detection/src/core/tests/filterMatchesBasedOnExceptions.ts
- packages/library-detection/src/libraries/gis/constants.ts
- packages/library-detection/src/libraries/gsi/constants.ts
- packages/library-detection/src/types.ts
1. It was suggested to reduce the loading delay of the known breakage section to 2 seconds. Additionally, the loader should display the message "Waiting for the page to load..." while the page is loading.
2. The issue was reported for false positive results on [cnn.com](http://cnn.com/). Sometimes it was observed that GIS feature `isDisplayed()` is being shown on [cnn.com](http://cnn.com/) under the known-breakages section.
A new configuration with the name `exception` has been added, which follows the following format:
```
{
"domain": ["string"]
}
```
If a match is found, results corresponding to the specified domain name will be excluded from the detected results.
This issue occurs infrequently. According to QA feedback, it primarily happens when the CDP is activated and a tab with the …
> Fix: Library detection miscellaneous QA issues

- packages/design-system/src/components/button/index.tsx
- packages/design-system/src/components/index.ts
- packages/design-system/src/components/toastMessage/index.tsx
- packages/extension/src/serviceWorker/index.ts
- packages/extension/src/utils/canProcessCookies.ts
- packages/extension/src/view/devtools/app.tsx
- packages/extension/src/view/devtools/components/settings/components/settingsContainer.tsx
- packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
- packages/extension/src/view/devtools/stateProviders/syncSettingsStore/index.tsx
- packages/extension/src/view/popup/app.tsx
- packages/extension/src/view/popup/stateProviders/syncCookieStore/index.tsx
- tailwind.config.cjs
This PR aims to remove the automatic reload of tabs if any extension setting is changed. Instead, a message will be shown to the user to click on reload all the tabs for settings to take effect and to get accurate data. This prevents the user from reloading the tab and losing any data.
- Session storage is used to store the data temporarily.
- Until the page is reloaded from our mechanism, the PSAT shows the settings from session storage.
- Once the page is reloaded with our mechanism extension settings storage is set and the PSAT takes value from the extension storage.
- Clone this branch and in the terminal run `npm start`.
- Go to any site and open the settings page. Switch any settings, and you should see a toast message at the bottom.
- You should see the same message in the popup. …
> Two-step process for toggling CDP state

- packages/extension/src/serviceWorker/index.ts
This PR aims to keep the service worker alive in case the profile with the extension is started.
- Add an interval for sending updated data from the service worker to the DevTools when re-opening a profile with the installed extension.
---
Partially addresses #509
> Fix: keep service worker alive

- packages/design-system/src/components/cookieDetails/details.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/namePrefixIconSelector.tsx
> Style-Fix: Scale up cookie prefix icon and update message text in cookie details.

- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/useHighlighting.tsx
It was observed that when any domain is allowed, and we move out of the frame to another frame and revisit, the green color disappears for a bit.
- Add `domainsInAllowList.size` as a dependency under `useHighlighting` hook. 
- Go to any frame for example on https://www.nationalgeographic.com/ and allow list some cookies.
- Go to cookies landing page and come back to the same frame. Same allow listed cookies should be highlighted.
---
- ~This code is covered by unit tests to verify that it works as intended~. NA
Fixes #
> Fix: Allow listed rows to highlight after frame change

- packages/extension/src/utils/findRWSURLSets.ts
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/insights/index.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/insights/utils/checkURLInRWS.ts
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/insights/utils/tests/checkURLInRWS.ts
This PR fixes the issue where ccTLDs were not processed while scanning through the RWS set.
- It updates the logic to retrieve the ccTLDs, scan them, and return the required data to the component.
- Adds UI to show the parent of the ccTLD on the RWS landing page's insight section.
---
Fixes #525
> Fix: Process ccTLDs and update UI in RWS

- packages/common/src/constants/index.ts
- packages/common/src/utils/filterCookiesByFrame.ts
- packages/design-system/src/components/sidebar/sidebarChild.tsx
- packages/design-system/src/components/sidebar/useSidebar/index.tsx
- packages/extension/src/view/devtools/app.tsx
- packages/extension/src/view/devtools/components/cookies/index.tsx
- packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
In this PR we aim to show the unmapped cookies that were received by CDP in the `Unknown frames` section.
- This majorly happens because `chrome.webRequest.onBeforeSendHeaders` doesn't capture the blocked request cookies because the browser excludes them even before being added to the request header.
- Since these excluded cookies were blocked from being read from `chrome.webRequest.onBeforeSendHeaders`.
- Now CDP receives the `extraInformation` of blocked cookies of a particular request. It sets the data for the cookie in the store. Since we do not yet have the association of this cookie with the `frameId` we do not show these cookies in the cookies table.
---
- ~~[ ] This code is covered by unit tests to verify that it works as intended.~~ NA
Fixes #524
> Fix: Show unmapped cookies from CDP in `Unknown Frames`

- packages/design-system/src/components/table/components/tableBody/bodyCell.tsx
- packages/design-system/src/components/table/components/tableBody/bodyRow.tsx
- packages/design-system/src/components/table/persistentSettingsStore/utils/extractStorage.ts
- packages/design-system/src/components/table/persistentSettingsStore/utils/updateStorage.ts
- packages/design-system/src/components/table/useTable/types.ts
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/index.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/namePrefixIconSelector.tsx
This PR aims to update the type of body-cell's prefix icon to be not wrapped into a function and rendered through a callback. Alongside now uses session storage for table persistence.
The icon key will contain `Element` that will hold the component function which will eventually be rendered inside bodycell as `<IconElement />`.
---
Fixes #
> Refactor: Update table storage and prefix icon type

- packages/extension/src/view/popup/stateProviders/syncCookieStore/index.tsx
This PR aims to fix a few issues including inconsistency in the CDP state in the settings page of `DevTools` and `Popup`. 
- Clone this PR and in the terminal run `npm start`.
- Open a fresh Chrome profile and install the PSAT extension.
- Oen any site and check the state of the CDP switch is inconsistent in the PSAT DevTools page and the PSAT popup.
---
> Fix: Inconsistency of CDP switch state.

- packages/cli-dashboard/src/hooks/useCookieListing.tsx/index.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/index.tsx
This PR updates the comparator of table filters to coercion an `undefined` value to a Boolean value.
- At times while selecting the HttpOnly filter's false value, the count of rows present was incorrect due to the `undefined` value present whose comparison was not handled in comparators.
- Open any website that has an `Unmapped Cookies` frame.
- Open the frame and open the filters sidebar.
- Find the HttpOnly filter, and click on false.
- You'll see the correct count of rows present.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/58820001/7b298072-c112-4037-a1bf-8d1492e4fda1
---
Fixes #
> Fix: Update filters comparator

- packages/design-system/src/components/table/components/tableBody/bodyRow.tsx
- tailwind.config.cjs
As we highlight the selected row in grey background color, it looses its original color during selection. This PR aims to change the selection color for each row.
- Update selection classes
- Visit any website for example bbc.com
- Allow list any third-party cookie so that its background becomes green.
- Check if the selection color is working as shown in the screencast.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/6297436/126d74da-5f06-4064-9cc4-16771e2c4a66
---
- ~This code is covered by unit tests to verify that it works as intended.~ NA
> Maintain selected row’s background color in row selection

- packages/extension/src/serviceWorker/index.ts
- packages/extension/src/utils/canProcessCookies.ts
This PR aims to correct the tool's scope classification and display correct first-party and third-party data.
- The problem happens sometimes because Chrome fires the event for an updated URL after a bit of delay by that time some 1p cookies are classified as 3p because they were being compared with the old tab URL. This PR uses the `pendingURL` if there is any to do the scope classification.
- In the terminal run `npm start`.
- Open a fresh browser instance and start analysing the tab using PSAT.
- Go to `nikkei.com` and check all the cookies that have nikkei.com as domain are being classified as `First Party`.
---
> Fix: Incorrect cookie scope classification

- packages/cli/src/index.ts
- packages/cli/src/procedures/analyzeCookieUrls.ts
It was observed that the CLI does not quit if the option to generate data into a directory is chosen. This PR fixes that.
- Add a browser de-initialization call after the cookie analysis is done.
- Add a `process.exit()` call to force the process to quit after the analysis is done.
- Follow the instruction in the `README.md` to build the cli.
- Use the command `npm run cli -- -u https://bbc.com/ -d ./bbc` to get an analysis report
- After the analysis is done the terminal process should end.
> Fix: CLI not quitting after generating output.

- packages/extension/src/serviceWorker/index.ts
- packages/extension/src/utils/getQueryParams.ts
- packages/extension/src/utils/tests/getQueryParams.ts
- packages/extension/src/view/devtools/stateProviders/syncSettingsStore/index.tsx
- packages/extension/src/view/popup/stateProviders/syncCookieStore/index.tsx
Enable CDP and multi-tab using query parameters, so that we can enable these settings when using [CLI commands ](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/Evaluation-Environment#spinning-chrome-instances-from-command-line)
- Go to any website like example.com and turn off CDP and mutlitab settings from PSAT settings section.
- Now go the some website like example.com and use the following query params https://example.com/?psat_cdp=on&psat_multitab=on
- The CDP and multi-tab settings should not be on.
---
Fixes #
> Feature: Enable CDP and multi-tab using query parameters

- packages/design-system/src/components/cookieDetails/details.tsx
- packages/design-system/src/components/table/components/tableBody/bodyRow.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/index.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/namePrefixIconSelector.tsx
This cookie changes highlighting logic in the cookie table and adds a new column named "Blocking Status".
The cookies who's blocking status is not determined ( previously signified by a ? icon) will have the value "Undetermined"
in the "Blocking Status" column. Also, such cookies will not be highlighted. the yellow highlight is reserved for blocked cookies.  
- Use the extension as per usual and visit any website.
- Any cookie previously shown with a question mark prefix icon and yellow highlight should have the value "Undetermined" in the newly added column named "Blocking Status"
- The cookie details panel should not have the explainer text for such cookies it has been moved to the tooltip in the table column "Blocking Status".
> Fix: Highlighting logic for undetermined blocking status cookie and create a new column for it

- packages/common/src/utils/getCookieKey.ts
- packages/extension/src/serviceWorker/index.ts
- packages/extension/src/store/synchnorousCookieStore.ts
- packages/extension/src/store/tests/synchnorousCookieStore.ts
- packages/extension/src/store/utils/updateCookieBadgeText.ts
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/tests/useHighlighting.tsx
This PR aims to normalise the cookie key by removing the `.` at the start of the domain.
- `getCookieKey` will check if the domain has a leading `.` then it will remove it else it will use it as is.
---
> Fix: Normalise cookie key to fix duplicate cookie issue

- packages/cli/src/index.ts
- packages/cli/src/utils/tests/validateArgs.ts
- packages/cli/src/utils/validateArgs.ts
Adds a new argument to the CLI interface '--dashboard-port' or '-po' which can be used to launch the CLI server on a chosen port.
- Naming the new argument CLI interface '--dashboard-port' or '-po'.
- Add a check that the user has chosen options for the dashboard to be launched before checking for any port conflicts.
- Use the cli command `npm run cli -- -u https://edition.cnn.com -po 9009`
- CLI dashboard should be launched on the chosen port.
- A service running on chosen port should not effect the CLI's functioning if its run in headless mode. `npm run cli -- -u https://edition.cnn.com -d ./out`
Fixes #573
> Feat: Add option to pass a port for development server

- packages/design-system/src/components/button/index.tsx
Add disabled state to the Button Component and refactor it to be more DRY.
---
> Refactor: Add disabled state to the Button component

- packages/common/src/constants/index.ts
- packages/extension/src/utils/getFramesForCurrentTab.ts
- packages/extension/src/utils/tests/getFramesForCurrentTab.ts
- packages/extension/src/view/devtools/components/cookies/cookieLanding/framesSection.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/index.tsx
This PR aims to hide the `priority` and `size` columns since they do not provide any useful information. This PR also aims to sweep some leftover references for `unmapped cookies` and `orphaned cookies` from the sidebar.
- Clone this branch. In the terminal run `npm start`.
- Open a fresh browser instance and go to `https://bbc.com`.
- There should be no `Unmapped Cookies` or `Orphaned Cookies` in the frames list.
- Click on any of the frames having cookies you should see the table without `priority` and `size` columns.
---
> Fix: Left over references and make some more space in the cookie table.

- packages/extension/src/view/devtools/components/cookies/cookieLanding/blockedCookiesSection.tsx
This PR adds code to allow user move from Blocked Cookies section description text to Settings page for enabling CDP.
It also updates the text of the description.
- Open Cookies landing page with CDP disabled.
- Scroll to blocked cookies section.
- The text below piechart will be contain new text with Settings page as clickable element.
- Click on text and it should open settings page.
---
Fixes #
> Navigate to `Settings` page from `Blocked Cookies` section

- packages/cli/src/utils/browserManagement/index.ts
- packages/cli/src/utils/browserManagement/parseNetworkDataToCookieData.ts
There were multiple copies of same copies with the only difference being a ".". This PR fixes that issue by adding a "." in front of all the cookie domains missing that. This approach is inspired by how the Chrome browser internally handles cookie domain.
- Analyze the website - https://rtcamp.com.
- There should not be multiple entries of the same cookie
> Fix: CLI dashboard showing multiple cookie entries for same cookies

- packages/design-system/src/components/errorFallback/extensionReloadNotification.tsx
- packages/extension/src/serviceWorker/index.ts
- packages/extension/src/view/devtools/app.tsx
- packages/extension/src/view/devtools/hooks/useContextInvalidated.ts
- packages/extension/src/view/devtools/stateProviders/cookie/cookieProvider.tsx
- This PR aims to fix the context-invalidated message shown on static sites. These are the sites which once loaded do not send requests to the server which hinders in reading of the cookies.
- This problem only occurs in the multitab environment.
- When the user opens PSAT in a multitab environment after the extension was updated they will be shown a context-invalidated message.
- Keep a website like https://www.clarin.com/ open in a tab with DevTool closed
- Go to chrome://extensions/
- Reload/Update the extension
- Go to https://www.clarin.com/ again and open DevTools
---
- ~This code is covered by unit tests to verify that it works as intended.~ NA
> Fix: Context invalidated for sites which do not send request after site is loaded

- packages/cli-dashboard/src/components/cookiesWithIssues/index.tsx
- packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesListing/index.tsx
Details panel was missing blocked reason section. Changing `isUsingCDP` prop value to true in CLI dashboard fixes it.
> Fix: CLI dashboard blocking reason

- packages/cli-dashboard/src/app.css
- packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesLandingContainer/cookieLanding/blockedCookiesSection.tsx
- packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesLandingContainer/cookieLanding/cookiesSection.tsx
- packages/design-system/src/components/cookiesLanding/cookiesLandingWrapper.tsx
- packages/design-system/src/components/cookiesLanding/cookiesMatrix/index.tsx
- packages/design-system/src/components/cookiesLanding/landingHeader/index.tsx
- packages/design-system/src/components/matrixContainer/index.tsx
- packages/extension/src/view/devtools/components/cookies/cookieLanding/cookiesSection.tsx
- packages/extension/src/view/report/components/cookiesSection.tsx
- Move the dropdown icon from right to extreme left in the sections of cookie landing page.
- Add note under cookies piechart saying `Please setup the evaluation environment before analyzing cookies.`, where click on evaluation environment should open wiki page.
- Remove info icon from categories, across extension, dashboard, report.
- Open cookies landing page, on extension, report, and dashboard
- The info icon on cookies section, alongside title Categories must not be present.
- On extension, a not should be present under cookies count piechart.
---
Fixes #
> Refactor: Update cookies section on the landing page

- packages/design-system/src/components/table/components/filtersSidebar/chips/index.tsx
- packages/design-system/src/components/table/components/filtersSidebar/tests/filtersSidebar.tsx
This PR updates the condition for showing clear all button even when one filter is selected.
Earlier implementation included showing of clear all button only when more than one filter is selected.
- Open cookie table, and click on filter icon to open filter sidebar.
- Dropdown any filter and select one value.
- The chips will appear above table and clear all button will be visible for one filter also.
---
Fixes #621
> Refactor: Update `Clear All` button render condition 

- packages/design-system/src/components/exportButton/index.tsx
- packages/design-system/src/components/menuBar/index.tsx
- packages/design-system/src/components/refreshButton/index.tsx
- packages/design-system/src/components/table/components/tableTopBar/index.tsx
- packages/design-system/src/icons/export.svg
This PR fixes the distorted icon of download button when visiting back from subpages on landing pages.
- Changed the svg used as download button, as it had some issue of misalignment causing distortion.
- Used icon from performance tab's download button.
- Open cookie table, and then visit multiple subpages.
- Come back to the landing page and icon should be consistent and no issue should be there.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/58820001/2973a5fd-cc3f-410c-8d9e-231b1ba58113
---
Fixes #624
> Fix: Broken download button icon

- webpack.shared.cjs
This PR aims to improve the build performance of our Webpack configuration by implementing caching for the Babel loader. By enabling this feature, we expect to see a significant reduction in build times, particularly during development, as Babel will be able to reuse previously computed results instead of reprocessing files from scratch on every build.
- Enabled caching in the Babel loader configuration within our Webpack setup.
To verify the effectiveness of this change:
1. Perform a clean build of the project and note the build time.
2. Make a minor change in one of the JavaScript/TypeScript files.
3. Rebuild the project and observe the build time. There should be a noticeable reduction in build time compared to the initial build.
4. Ensure that the application still runs as expected …
> Feature: Update `babel-loader` webpack config to have caching support for faster builds

- packages/library-detection/src/components/accordion/accordionContent.tsx
- packages/library-detection/src/components/accordion/accordionHeading.tsx
- packages/library-detection/src/components/accordion/detectionMessage.tsx
- packages/library-detection/src/components/accordion/index.tsx
- packages/library-detection/src/components/libraryDetection/index.tsx
- packages/library-detection/src/libraries/disqus-comments/accordion.tsx
- packages/library-detection/src/libraries/disqus-comments/tests/accordion.tsx
- packages/library-detection/src/libraries/fb-comments/accordion.tsx
- packages/library-detection/src/libraries/fb-comments/tests/accordion.tsx
- packages/library-detection/src/libraries/fb-likes/accordion.tsx
- packages/library-detection/src/libraries/fb-likes/tests/accordion.tsx
- packages/library-detection/src/libraries/gis/accordion.tsx
- packages/library-detection/src/libraries/gsi/accordion.tsx
- packages/library-detection/src/libraries/jetpack-comments/accordion.tsx
- packages/library-detection/src/libraries/jetpack-comments/tests/accordion.tsx
- packages/library-detection/src/libraries/jetpack-likes/accordion.tsx
- packages/library-detection/src/libraries/reCaptcha/accordion.tsx
- packages/library-detection/src/libraries/reCaptcha/tests/accordion.tsx
This PR updates UI in the known breakages section
- Click on each accordion item to expand it.
- Verify that the box UI surrounding the expanded item disappears.
- Scroll through the list of items.
- Check that there is no separator line after the last item in the list.
- Navigate to the GIS & GSI section.
- Check that the bullets or feature list items are not visible.
- Review each detection title.
- Confirm that there are no full-stops (periods) at the end of the titles.
- Verify that the titles are shortened to a standardized length.
- Verify that the Call to Action (CTA) beneath each detection is more informative.
---
Fixes #642
> Refactor: Update `Known Breakages` component UI

- packages/library-detection/src/core/stateProvider/index.tsx
This issue fixes the messaging that is displayed in the known breakages section when a link is quickly opened and closed.
---
Fixes #635
> Fix: Known breakages section throwing error when a link is quickly opened and closed

- packages/extension/src/serviceWorker/index.ts
This PR aims to normalise blocking reasons that are being added from different APIs.
- Essentially `ExcludeThirdPartyPhaseout` and `ThirdPartyPhaseout` are actually the same, the only difference is they come from different APIs.
- Open a Chrome instance with a 3PCD-enabled flag.
-  Go to any website with 3rd party cookies.
- You should see only ThirdPartyPhaseout as a blocking reason, not ExcludeThirdPartyPhaseout
---
> Fix: Normalise blocking reason.

- packages/extension/src/view/devtools/components/facilitatedTesting/faciliatedTestingContent/infoCards.tsx
This PR adds code to add Readiness section inside `Facilitated Testing`  landing page's infocards.
- Open PSAT panel, navigate to Facilitated Testing landing page.
- Scroll vertically to find `Readiness` heading with content in infocards.
- The content should contain a link, click on it should open [this page](https://github.com/privacysandbox/privacy-sandbox-dev-support/blob/main/3pcd-readiness.md).
---
Fixes #612
> Add readiness content in `Facilitated Testing` section

- packages/extension/src/view/devtools/components/facilitatedTesting/faciliatedTestingContent/infoCards.tsx
This PR updates the content in facilitated testing page
- Moves Readiness section to the top of list.
- Renames the title to `Third-Party Cookie Depreciation Readiness`.
- Open PSAT panel and navigate to Facilitated testing section.
- Infocards section's first item must be `Third-Party Cookie Depreciation Readiness`.
- Click on url should open new page and open github repo [here](https://github.com/privacysandbox/privacy-sandbox-dev-support/blob/main/3pcd-readiness.md).
---
Fixes #
> Update 3PCD readiness section

- packages/extension/src/serviceWorker/index.ts
- packages/extension/src/store/synchnorousCookieStore.ts
- This issue fixes the zero cookie issue that occurs randomly while doing cookie analysis.
- Move setInterval from service worker to new objectCreation of SynchnorousCookieStore.
---
> Fix: Zero cookie issue.

- packages/common/src/data/index.ts
- packages/extension/src/serviceWorker/index.ts
This PR aims to add create a map between cookie exclusion reason and cookie blocked reason to normalise the cookie blocked reason.
---
> Fix: Map exclusion reason to cookie blocked reason.

- packages/extension/src/view/devtools/components/cookies/cookiesListing/rowContextMenu.tsx
- packages/extension/src/view/devtools/components/cookies/tests/rowContextMenu.tsx
This PR adds an API that will allow navigation to the network panel from PSAT.
This API is available in the Chrome version 125.
On old Chrome versions, the old functionality of copying network filter string from context menu will continue.
- Open Chrome v125, and install PSAT.
- Start analyzing a tab, and move to the cookie table.
- Right-click on any row and the dialog box should open.
- The first item should say 'Show Requests With This Cookie', click on it will open the network panel with filter inside the input bar.
- The rows in network will be filtered according to the cookie name and domain provided.
- Try the same Chrome v124 or below now, this should not open the network panel and continue the old functionality copying filter to the clipboard. …
> Feature: Navigate from PSAT to network panel

- packages/cli-dashboard/src/hooks/useCookieListing/index.tsx
- packages/design-system/src/components/table/components/tableBody/bodyCell.tsx
- packages/extension/src/view/devtools/components/cookies/cookiesListing/rowContextMenu.tsx
- packages/extension/src/view/devtools/components/layout.tsx
This PR 
- Updates the filter key used in CLI for the same site, which will now show correct data.
- Remain on the same frame if the hostname is the same as the previous URL, inside the extension.
- Close the context menu on the table row once the user has navigated to the network panel.
- Correct the dom elements nesting to not get errors inside the console.
- Run analysis of site on CLI.
- Let the dashboard open, and open the cookie table.
- Select the SameSite filter and rows should be filtered correctly.
- Now open the PSAT panel in dev tools and analyze livemint.com
- Open the first frame and now click a link inside the web page.
- Navigation to a new page of the same hostname should keep the first frame selected.
- Now right click on any row and context menu should open.
- Click on …
> Fix: Update UX functionality of components

- packages/common/src/index.ts
- packages/common/src/utils/mergeDeep.ts
- packages/common/src/utils/tests/mergeDeep.ts
- packages/design-system/src/components/table/persistentSettingsStore/utils/updateStorage.ts
- packages/design-system/src/components/table/useTable/types.ts
- packages/design-system/src/components/table/useTable/useFiltering/hooks/index.ts
- packages/design-system/src/components/table/useTable/useFiltering/hooks/tests/useFiltersExtraction.tsx
- packages/design-system/src/components/table/useTable/useFiltering/hooks/tests/useFiltersOptions.tsx
- packages/design-system/src/components/table/useTable/useFiltering/hooks/useFiltersExtraction.tsx
- packages/design-system/src/components/table/useTable/useFiltering/hooks/useFiltersOptions.tsx
- packages/design-system/src/components/table/useTable/useFiltering/hooks/useFiltersPersistence.tsx
- packages/design-system/src/components/table/useTable/useFiltering/index.tsx
This PR adds code to persist filters when the user refreshes the web page.
- When the table is opened, saved filters are extracted and applied.
- As time moves, the user keeps selecting filters, and we keep updating the storage.
- When the user navigates to another table, we extract and apply filters.
- So the flow continues to open the PSAT panel, open the table, apply filters, navigate to other tables, and close the PSAT.
- But if we count the reloading of the page as a step to fulfill, the data gets lost, how?
- During the debugging process, when the table is opened the first time we extract saved filters, let's say this time as T1.
- As the user starts selecting different filters and reaches time T4.
- During this time frame, storage has been updated but the local state storing …
> Fix: Persist filters after web page reload

- packages/cli/src/utils/browserManagement/index.ts
- packages/cli/src/utils/browserManagement/parseNetworkDataToCookieData.ts
This PR fixes some cookies not being highlighted on livemint.com
1. `isBlocked` is recalculated in `parseNetworkDataToCookieData`
1. Run `npm run cli -- -u https://livemint.com/`
2. Open CLI Dashboard and the `ppid` cookie should be highlighted
---
Fixes #680
> Fix: inconsistent highlighting on livemint.com

- packages/cli-dashboard/src/app.tsx
- packages/cli-dashboard/src/components/siteMapReport/index.tsx
- packages/cli-dashboard/src/components/siteMapReport/layout.tsx
- packages/cli-dashboard/src/components/siteReport/index.tsx
- packages/cli-dashboard/src/components/siteReport/stateProviders/contentStore/index.tsx
- packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesListing/index.tsx
- packages/design-system/src/components/cookieTable/index.tsx
- packages/design-system/src/components/cookieTable/utils/exportCookies.ts
- packages/extension/src/view/devtools/components/cookies/cookiesListing/index.tsx
This PR adds code to add hostname as a prefix to the cookie table CSV.
- Open the PSAT panel and open the cookie table.
- Click on the download icon beside the search bar.
- A file should be downloaded and the file name should include hostname as a prefix.
- For eg. website is https://livemint.com, the file should be `www-livemint-com-report.csv`
---
Fixes #688
> Add website hostname as prefix to cookie table CSV

- packages/report/src/index.tsx
The function of `chrome.tabs.get` which was added to the library detection was not mocked and this caused the dowloaded report to break. This PR aims to fix this issue.
- In the terminal run `npm run cli:build && npm run cli -- -u https://bbc.com`
- Now download the report from cli-dashboard.
- Check the html report.
- The error for `chrome.tabs.get` should not be present anymore.
---
> Fix: Report throwing error when downloaded from CLI.

- packages/cli/src/index.ts
- packages/cli/src/utils/validateArgs.ts
- packages/design-system/src/components/menuBar/tests/isElementInView.ts
This PR aims to add a default argument to the CLI which will be the website URL and will allow the user to analyse the website without requiring to use the `-u` option.
If the user wants to use the `-u` option, it will still be available.
- Add optional argument using `.argument` function from `commander.js`
- In the terminal run `npm run cli:build`.
- Now in the terminal run `npm run cli https://bbc.com`.
- This should analyse `bbc.com` website.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/59614577/89826e59-4d24-475a-9b28-f31ca4a6df70
---
- ~~[ ] This code is covered by unit tests to verify that it works as intended.~~NA
> Feature: Provide an optional argument to CLI.

- data/PSInfo.json
- packages/design-system/src/components/landingPage/infoCard/fetchPSInfo.ts
- packages/design-system/src/components/landingPage/infoCard/index.tsx
- packages/design-system/src/components/landingPage/infoCard/learnMoreDropdown.tsx
This PR adds the useI18n key value inside InfoCard so as not to use getMessage for non-translated strings.
- Configure the system for a locale other than English and open PSAT.
- Navigate to the Protected Audience landing page, the text should be visible in English without any breakage.
- Now compare the same with the `develop` branch.
---
Fixes #
> Fix: Conditionally use `I18n.getMessage` function inside `InfoCard`

- package-lock.json
- packages/cli/package.json
- packages/cli/src/index.ts
- packages/i18n/src/i18n.ts
- packages/i18n/src/tests/i18n.ts
This PR aims to make CLI work when its published on NPM as well as when the repository is cloned.
- Use different paths to get the CLI dependencies.
For local installation:
- Go to terminal and run `npm run build-cli`.
- Now run `npm run cli https://natgeo.com`
- You should be able to see the report.
For global installation:
- Go to terminal and run `npm run local-registry:start && npm run publish:all:local`.
- Then open new terminal instance ther run `npm i -g @google-psat/cli && psat https://bbc.com`.
- You should be able to see the report.
---
> Fix paths for cli to work on global as well as local installation.

- packages/analysis-utils/src/browserManagement/index.ts
This PR fixes an intermittently occurring error bug when analyzing sites.
> CLI: Fix missing frame key in the page frames Hashmap

- packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesLandingContainer/cookieLanding/blockedCookiesSection.tsx
- packages/common/src/cookies.types.ts
- packages/common/src/data/cookieExclusionAndWarningReasons/cookieBlockedReason.ts
- packages/common/src/index.ts
- packages/common/src/utils/getLegendDescription.ts
- packages/design-system/src/components/cookieDetails/details.tsx
- packages/design-system/src/components/cookiesLanding/cookiesMatrix/index.tsx
- packages/design-system/src/constants.ts
- packages/design-system/src/theme/colors.ts
- packages/design-system/src/utils/prepareCookieStatsComponents.ts
- packages/design-system/tsconfig.json
- packages/extension/src/view/devtools/components/cookies/cookieLanding/blockedCookiesSection.tsx
- packages/extension/src/view/devtools/components/cookies/cookieLanding/exemptedCookiesSection.tsx
- packages/extension/src/view/devtools/components/cookies/cookieLanding/framesSection.tsx
- packages/report/src/components/blockedCookiesSection.tsx
- packages/report/src/components/framesSection.tsx
- tailwind.config.cjs
- test.csv
This PR adds more blocked reason and handles message to be displayed where there is not translated content
- Clone this branch and in the terminal run `npm run build:all`.
- Run the PSAT CLI on following URL using the command. `npm run cli https://time.com -- -l hi`.
- You should see the dashboard without breakages and the new blocked reason in English.
- Similarly, the extension should also not break for the site time.com.
---
> Add more blocked reasons content.

- packages/extension/src/serviceWorker/chromeListeners/index.ts
- packages/extension/src/serviceWorker/chromeListeners/onCommittedNavigationListener.ts
On some sites it was noticed the tab doesnt reload but due to ads the tab was moved to loading state. This PR aims to use `onCommitted` listener from `chrome.webNavigation` which fixes the resetting of cookie stats issue.
- Use `onCommitted` listener from `chrome.webNavigation` instead of `chrome.tabs.onUpdated`.
- In the terminal run `npm run ext:build`
- Now in the browser open `beebom.com`
- Go to any article and keep on scrolling you should see that the cookie stats do not reset now.
---
> Fix: Use onCommittedNavigation Listener instead of onTabUpdated

- packages/design-system/src/components/index.ts
- packages/design-system/src/components/tabs/index.tsx
- packages/design-system/src/components/tabs/tests/index.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/index.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/insights/index.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/components/input/index.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/index.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/tests/jsonGenerator.tsx
- packages/extension/src/view/devtools/e2e-tests/rwsMembership/index.ts
- tailwind.config.cjs
This PR adds tabs based navigation inside landing pages.
- The `Tab` and `Shift + Tab` keys can also be used for navigation inside the landing page.
- Open the PSAT panel and navigate to RWS.
- Once opened, tabs-based UI should be visible.
- Using `Tab` and `Shift + Tab` will also respond to navigation.
---
Fixes #780
> Feature: Add tabs navigation inside landing page

- packages/analysis-utils/src/browserManagement/index.ts
- packages/cli/src/index.ts
- packages/cli/src/utils/validators.ts
- packages/extension/src/view/devtools/test-utils/puppeteerManagement.ts
This pull request corrects some sentences on the output messages from the CLI and improves some sentences to make them clear
1. Open the CLI on the terminal 
2. Run a audit with verbose mode `$ psat https://example.com -v`
3. Check the output messages
---
Fixes #807
> Fixing CLI output typo and improve text

- package-lock.json
- packages/analysis-utils/src/browserManagement/index.ts
Imrprove the consent acceptance quality.
Added the as additional consent acceptance the term "ok" .
Test with [otto.de](http://otto.de/) and [manufactum.com](https://www.manufactum.com/) website where it requires to click "ok" to accept the cookie consent.
The test with local environment ```npm run cli -- --display https://www.manufactum.com``` displayed that the button "ok" being successfully clicked. 
---
We have tried to run the test locally with command  npm run test:cli:e2e
but we got following errors and could not complete.
CLI E2E Test
✕ Should run site analysis (8537 ms)
● CLI E2E Test › Should run site analysis
assert.strictEqual(received, expected)
Expected value to strictly be equal to:
true
Received:
false
Message:
should match stdout expected includes …
> Add "ok" for gdpr consent button lookup.

- packages/design-system/src/components/sidebar/useSidebar/constants.ts
- packages/extension/src/view/devtools/components/privateAdvertising/privateAdvertising.tsx
- packages/extension/src/view/devtools/tabs.ts
This PR aims to reorder the items in the sidebar.
- Clone the branch.
- In the terminal run `npm i` and then run `npm run build:ext`.
- You should see the order in PAT section as follows:
1. Topics
2. Protected Audience
3. Attribution Reporting
4. Private Aggregation
---
Fixes #824
> Refactor: Update order of PAT Section components

- packages/common/src/utils/generateReports/generateRootSummaryDataCSV.ts
The PR aims to modify the generated CSV for a sitemap, where the count for each URL is provided along with the aggregated counts.
- Clone this PR.
- In the terminal run `npm i` && `npm run build:cli`.
- Now run analysis on a sitemap with `-o` or download the zip from the CLI-dashboard.
---
Fixes #850
> Feature: Include individual site summaries in the aggregated report of a sitemap

- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/topics/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/topics/taxonomyTree/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/topics/taxonomyTree/tree.js
This PR fixes issues on PAT panels
- EE PAT doesn't have animation integrated, so removed it from the tabs.
- Handle the issue of the search not working if the root node is closed.
- Handle highlighting of the node on the path of the searched node.
- Search bar in sticky in Topics Taxonomy tree
- Open PSAT and navigate to the Protected Audience panel.
- The EE tab should not be visible.
- Now navigate to the Topics panel.
- Inside the Taxonomy panel, collapse the root and search for any topic.
- It should open the correct path for the topic.
- Now search `TV dramas` in the search bar, and open the tree path through the dropdown.
- Click on Arts and Entertainment node, and close child nodes.
- Again search for `TV dramas`  and open it.
- It should highlight all the nodes on the path.
---
- …
> Fix: Issues on PAT panels

- packages/cli/README.md
- packages/cli/src/index.ts
This pull request is related to issue #843, updating the helper message for the option `--button-selectors`
Standardize the name convention for the technologies listed and use better wording on the CLI messages.
1. install PSAT CLI
2. Run the command `npm run cli -- -h`
3. Check the message
---
Fixes #843
> Improve helper message for the GDPR banner parameter

- packages/explorable-explanations/public/index.html
- packages/explorable-explanations/src/components/branches.js
- packages/explorable-explanations/src/components/progressLine.js
- packages/explorable-explanations/src/lib/ripple-effect.js
- packages/explorable-explanations/src/lib/utils.js
- packages/explorable-explanations/src/modules/auctions.js
- packages/explorable-explanations/src/modules/bubbles.js
- packages/explorable-explanations/src/modules/join-interest-group.js
- packages/explorable-explanations/src/modules/timeline.js
- packages/explorable-explanations/src/protectedAudience.js
This PR aims to add Previous and Next buttons to the canvas where in if the user is in non-interactive mode and clicks on next button the user icon will move into the next website.
- Clone this branch
- In the terminal run `npm run dev:ee:pa`.
- Now when animation is running click on next and previous button to see the effect
https://github.com/user-attachments/assets/f1d12af1-62d6-4896-90ed-df97aeb4c17f
---
- ~[x] This code is covered by unit tests to verify that it works as intended.~
> Feature: Add previous and next buttons for EE PA

- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/interestGroups/index.tsx
- packages/extension/src/view/devtools/stateProviders/protectedAudience/protectedAudienceProvider.tsx
- packages/extension/src/view/devtools/stateProviders/protectedAudience/utils/computeInterestGroupDetails.ts
In this PR, we are updating the interest group tables data only having `join` or `leave` events and filtering out the rest.
- In the terminal run `npm i && npm run build:ext`.
- Go to example.com and enable CDP and multi-tab debugging.
- Now in the same tab go to https://psat-pat-demos-shop.dev/items/1f45f
- Then in another tab go to https://psat-pat-demos-news.dev/
- The Interest Group Table in Protected Audience should now only show join events and not the bid and win events.
> Fix: Update Interest group table to show only join and leave events

- packages/explorable-explanations/src/protectedAudience/canvas/setupMainCanvas.js
- packages/explorable-explanations/src/protectedAudience/components/box.js
- packages/explorable-explanations/src/protectedAudience/components/progressLine.js
- packages/explorable-explanations/src/protectedAudience/config.js
- packages/explorable-explanations/src/protectedAudience/index.js
- packages/explorable-explanations/src/protectedAudience/modules/auctions.js
- packages/explorable-explanations/src/protectedAudience/modules/timeline.js
- Change background to white and fix circle override
- Change circle color to visited green after visit
- Show info info to only boxes with info
- Fix arrows not taking colors.
- Use `smooth()` for main canvas
- Create separate functions for setting up ad auction, ssp flow, branches and ad unit code
---
> PA EE code refactoring and small fixes

- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/auctions/auctionTable.tsx
This PR updates the key from `formattedTime` to `time`, used for showing Event time.
This change makes the sorting comparison based on ms in `number`.
In UI, the `formattedtime` key will be rendered to the event time, as it is already calculated while creation the data array in the service worker.
- Navigate to https://privacysandboxdemos.domain-aaa.com/
- Open PSAT and navigate to Protected Audience -> Auctions.
- Add IG and run an auction, the table should get updated.
- Click on the Event time column, it should sort the rows correctly based on time.
---
Fixes #
> Fix: Use `time` key for `Event Time` column

- packages/explorable-explanations/src/protectedAudience/index.js
- packages/explorable-explanations/src/protectedAudience/modules/auctions.js
- packages/explorable-explanations/src/protectedAudience/modules/flow.js
- packages/explorable-explanations/src/protectedAudience/modules/joinInterestGroup.js
- packages/explorable-explanations/src/protectedAudience/modules/timeline.js
- packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/index.js
- packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseClickedInInteractiveModeCallback.js
- packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseClickedInNonInteractiveModeCallback.js
- packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseMovedInTimeline.js
Previously, we added a double arrow drop down in the interactive mode to show the non-animated flow. The same has been applied in the non-interactive mode as well.
- Clone this branch
- In the terminal run `npm i && npm run dev:ee:pa`.
- Now see when the animation is running, note that the double down arrow has opacity and pointer default indicating the arrows are not clickable.
- Once all the circles have been visited, the double down arrow opacity is removed and the icon is not clickable.
- This only works when all the circles have been visited and whole flow is completed.
---
~~- [ ] The QA of this PR is done by a member of the QA team (to be checked by QA).~~ NA
> Feature: Add double dropdown arrow in non interactive mode to show non animated flow.

- packages/design-system/src/components/table/components/index.tsx
- packages/design-system/src/components/table/components/tableBody/bodyRow.tsx
- packages/design-system/src/components/table/components/tableBody/tests/bodyRow.tsx
- packages/design-system/src/test-data/cookieTableMockData.tsx
- packages/explorable-explanations/src/protectedAudience/modules/bubbles.js
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/panel.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/tableTabPanels/info.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/interestGroups/table.tsx
This PR adds code for the autoscrolling table to the highlighted row.
- When an IG bubble is clicked, the related row to that IG will be highlighted, and if the row is outside the screen preview, the table auto-scrolls to the required row.
- This is not limited to the IG table, the changes are inside the table's body row, so if any table has enabled highlighting, this logic should work.
- Alongside this PR also updates the comparison logic for highlighting by comparing the owner of the IG.
https://github.com/user-attachments/assets/1e6cd7f2-dba6-44d4-814a-a76e43175f87
---
> Enhancement: Autoscroll table on row highlighting

- packages/explorable-explanations/src/index.js
- packages/explorable-explanations/src/protectedAudience/config.js
- packages/explorable-explanations/src/protectedAudience/modules/auctions/index.js
- packages/explorable-explanations/src/protectedAudience/modules/auctions/multi-seller/setUpComponentAuctions.js
- packages/explorable-explanations/src/protectedAudience/modules/auctions/setUpAdUnitCode.js
- packages/explorable-explanations/src/protectedAudience/modules/auctions/setupBranches.js
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/auctions/panel/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/auctions/table/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/auctionEventTransformers.ts
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/constants.ts
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/index.tsx
This PR updates the synthetic data for differentiation across all publisher nodes.
- Adds a new publisher at the end of the timeline.
- Fix the data time for the auction table.
- Update synthetic data to create a variable `publisherData` for different data.
- Matches the date time of publisher nodes in the branches, the sidebar to the circle time.
- Different SSP titles and URLs for each publisher node.
- Different adunit codes for each publisher node.
---
> Enhancement: Update synthetic data for distinction

- packages/extension/src/view/devtools/tabs.ts
Move settings from bottom to the top in the sidebar
Remove spacer added to the previous item in the sidebar
1. Pull the branch `fix/setting-menu-item`
2. Build the project npm run build:all
4. Navigate to example.com
5. Open privacy sandbox tab on DevTools
6. Observer: the "Settings" sidebar item is under the "Wiki" item at the top, not in the bottom
- Before:
- After:
- NA ~[ ] This code is covered by unit tests to verify that it works as intended.~
> Fix: Move settings from bottom to the top in the sidebar

- packages/explorable-explanations/src/protectedAudience/index.js
- packages/explorable-explanations/src/protectedAudience/modules/bubbles.js
- packages/explorable-explanations/src/protectedAudience/modules/timeline.js
- packages/explorable-explanations/src/protectedAudience/utils/drawOpenArrowWithoutAnimationIcon.js
- packages/explorable-explanations/src/protectedAudience/utils/index.js
- packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseClickedInInteractiveModeCallback.js
- packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseClickedInNonInteractiveModeCallback.js
- packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseMovedInInteractiveMode.js
- packages/extension/src/view/devtools/components/explorableExplanation/header.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/auctionEventTransformers.ts
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/panel.tsx
- packages/extension/src/view/devtools/index.tsx
This PR aims to fix EE bugs and issues that were found in the QA of Explorable Explanations.
The following is a checklist of the errors fixed in this PR:
---
> Fix: Explorable explanation bugs and minor issues

- packages/design-system/src/components/tabs/index.tsx
- packages/design-system/src/components/tabs/tests/index.tsx
- packages/design-system/src/components/tabs/useTabs/context.ts
- packages/design-system/src/components/tabs/useTabs/provider.tsx
- packages/design-system/src/components/tabs/useTabs/tests/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/panel.tsx
- tailwind.config.cjs
This PR adds code to handle tab highlighting.
- `highlightTab` callback highlights the tab with a bubble alongside the title.
- `count` param is used to set tab updates count.
- `increment` param is used to increment the update count.
- Navigate to PA EE, let the animation run.
- When the user reaches publisher site, the tabs should not auto switch.
- The auction and bids tabs should be highlighted.
- Once the highlighted tab is navigated to, the bubble should disappear.
---
> Feature: Add tab highlighting capabilities

- packages/extension/src/view/devtools/components/antiCovertTracking/antiCovertTracking.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/privateAdvertising.tsx
- packages/extension/src/view/devtools/components/siteBoundaries/siteBoundaries.tsx
Brings back the dummy story link for testing in for all the cards in all the sections.
N/A
1. Build the extension from source.
2. Verify the presence of dummy web story link in all the cards in all sections.
---
> Bring back the story links for all cards in all sections

- packages/design-system/src/components/index.ts
- packages/design-system/src/components/link/index.tsx
- packages/explorable-explanations/src/protectedAudience/modules/flowConfig.jsx
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/tableTabPanels/legend.tsx
This PR removes the "General Use" section from the Info tab and add details to the Legend tab. It also adds details for the interest group symbols used in the flow.
NA
1. Open PA:EE and click on the info icon of each box for advertiser, single and multi-seller auctions.
2. Read the info text used for every box and ensure that they make sense and there is no typo.
3. Open Legend tab and read it's content.
> Explorable Explanation: Add legend content and remove 'General Use' from info tab

- packages/extension/src/view/devtools/components/privateAdvertising/topics/explorableExplanation/animation.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/topics/explorableExplanation/index.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/topics/explorableExplanation/legend.tsx
- packages/extension/src/view/devtools/components/privateAdvertising/topics/explorableExplanation/panel.tsx
This PR adds a legend tab to topics EE.
- The legend tab contains general information about topics EE.
- Open PSAT and navigate to topics EE.
- Open the Legend tab, the tab should contain basic information about topics.
- Switch between tabs should not affect the EE, no distorted figures should be present.
https://github.com/user-attachments/assets/92401e3f-59ae-4fcc-aaee-05f073e445e5
---
Partially addresses #856
> Feature: Add topics legend tab

- packages/design-system/src/components/link/index.tsx
- packages/extension/src/view/devtools/components/privacySandbox/contentPanel.tsx
This PR  opens 'Learn More' button on the privacy sandbox landing page in the same tab.
- Use `Link` component from the `design-system` package instead of `<a>` tag.
- Extend `LinkProps` interface to accept more attributes.
Go to privacy sandbox landing page and click on "Learn More" button. It should open in the same tab.
---
Fixes #
> Open "Learn More" button link in the same tab

- packages/design-system/src/components/landingPage/contentPanel.tsx
- packages/design-system/src/components/landingPage/infoCard/renderLink.tsx
Replace anchor tags with the `Link` component in Landing page info cards and other meta links.
Uses the `Link` component to open the links in the same tab instead of opening in a new tab for links within info cards of Landing pages and other meta links on the those pages.
1. Navigate to any landing page.
2. Click on the documentation link in the info card.
3. Verify that the link opens in the same tab instead of opening in a new tab.
N/A
N/A
---
> Replace anchor tag with `Link` component in Landing page info cards

- packages/explorable-explanations/src/protectedAudience/modules/bubbles.ts
- packages/extension/src/view/devtools/app.css
- packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/panel.tsx
Remove jumpy animation when minifying bubbles
1. Pull the branch fix/add-missing-api-pages
2. Build and run project the project: npm run build:all && npm run dev:ext
3. Open privacy sandbox tab on DevTools
4. Go to Private advertising section
5. Open Explorable explanations panel
6. Observe: the animation start
7. Click the bubble in the corner left
8. Observe: the bubble animates correctly, going from the top left corner to the center of the container
9. Click the close button
10. Observe: the bubbles correctly, going from the center of the container back to the top left corner
Maker sure to test with different number of bubbles in inside the main bubble and when the diagram get big enough to make scrolling appear in the container
- Before: …
> Fix: Bubble minify animation

- packages/design-system/src/components/landingPage/contentPanel.tsx
- packages/design-system/src/components/landingPage/index.tsx
- packages/extension/src/view/devtools/pages/antiCovertTracking/antiCovertTracking.tsx
- packages/extension/src/view/devtools/pages/privateAdvertising/privateAdvertising.tsx
- packages/extension/src/view/devtools/pages/siteBoundaries/siteBoundaries.tsx
This PR links each card title and icon used in the landing pages to the related pages.
- Use `updateSelectedItemKey` to navigate user to the related pages.
- Use additional `sidebarItemKey` to pass `SIDEBAR_ITEMS_KEYS`.
- Visit "Site Boundaries", "Private Advertising" and "Tracking Protection" pages.
- Click on the icon and title of each card and ensure that they go to the correct pages.
---
Fixes #
> Feature: Link landing page cards to related pages

- .github/workflows/tests-unit-js.yml
- packages/extension/src/view/devtools/e2e-tests/settings/index.ts
This PR updates actions/cache from an older version to v3.4.0 to ensure compatibility with GitHub’s new cache storage architecture. 
- GitHub is deprecating older versions (v1, v2, and some v3 versions) of actions/cache.
- After March 1, 2025, workflows using deprecated versions will fail.
- Brownouts will occur before full deprecation, causing temporary failures.
See [notice](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down)
---
- ~[ ] The QA of this PR is done by a member of the QA team (to be checked by QA).~ NA
> Upgrade actions/cache to v3.4.0 to prevent deprecation issues

- packages/explorable-explanations/src/protectedAudience/components/box.ts
- packages/explorable-explanations/src/protectedAudience/components/info.ts
Fixing logic of the box info icon
1. Pull and checkout the branch `fix/ee-box-info-icon`
4. Go to Private Advertising
5. Go to Explorable Explanations tab
6. Observe: the Boxes in the diagram show an info icon
7. Click the icon
8. Observe: the bottom panel is updated with the information
- [NA] This code is covered by unit tests to verify that it works as intended.
> Fix: EE box info icon

- packages/design-system/src/components/frameContent/index.tsx
- packages/extension/src/view/devtools/pages/layout.tsx
- packages/extension/src/view/devtools/pages/learning/landingePage.tsx
Make learning pages responsive and remove bold from description in framed content
1. Pull and checkout the branch `fix/learning-page-responsive`
4. Go to Learning Section
5. Visit the following pages: Dev Site, Help Center and Wiki
6. Observer: the content adapts to different screen sizes
- NA This code is covered by unit tests to verify that it works as intended.
> Fix: Learning page responsive

- scripts/update-cookie-db.cjs
This pull request maps the cookies under the categories of personalization and security to functional, fixing issue #889.
The 27 cookies categorized as personalization and security from the cookie database were listed as uncategorized when they were listed on the cookie database. This pull request changes the script `update-cookie-db.cjs` responsible for reading the cookies from the cookie database and converting it into JSON format. The change maps the categories `security` and `personalization` as `Functional` to not impact the current categorization. 
1. Pull the branch `fix/security-personalization-categories`
2. Run the command `npm run cookie-db:update`  to update the cookie database
3. Build the project `npm run build:all`
4. Navigate to `globo.com`
5. Open the cookie table at the …
> Mapping categories under personalization and security to Functional

- .github/workflows/tests-unit-js.yml
- packages/design-system/src/components/landingPage/contentPanel.tsx
- packages/design-system/src/components/landingPage/index.tsx
- packages/extension/src/view/devtools/app.tsx
- packages/extension/src/view/devtools/e2e-tests/settings/index.ts
- packages/extension/src/view/devtools/pages/dashboard/constants.ts
- packages/extension/src/view/devtools/pages/dashboard/contentPanel.tsx
- packages/extension/src/view/devtools/pages/layout.tsx
- packages/extension/src/view/devtools/pages/privacyProtection/privacyProtection.tsx
- packages/extension/src/view/devtools/pages/privacyProtection/tests/index.tsx
- packages/extension/src/view/devtools/pages/siteBoundaries/siteBoundaries.tsx
- packages/extension/src/view/devtools/tabs.ts
- packages/extension/src/view/devtools/test-utils/interaction.ts
This PR does the following changes
- Test if all of the above items have been addressed without creating regression.
- Since the order of the menu items have changed and cookies page has been moved inside "Tracking Protection", see if it creates any regression issue specially preserving page visits.
---
Fixes #
> Reorder menu items and misc UI changes

- packages/common/src/protectedAudience.types.ts
- packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/adUnits/adTable.tsx
- packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/auctions/adunitPanel/panel.tsx
- packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/bids/receivedBidsTable.tsx
- packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/explorableExplanation/auctionEventTransformers.ts
- packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/explorableExplanation/interestGroupTransformer.ts
- packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/interestGroups/table.tsx
- packages/extension/src/view/devtools/stateProviders/protectedAudience/protectedAudienceProvider.tsx
- packages/extension/src/view/devtools/stateProviders/protectedAudience/utils/computeReceivedBidsAndNoBids.ts
This PR aims to solve Ad Container Size showing undefined in the receivedBids Table.
- Open a fresh instance of chrome with the extension installed.
- Now go to [ privacysandboxdemos-domain-aaa.com.](https://privacysandboxdemos.domain-aaa.com/publisher/)
- Then join all the interest groups.
- Now click on run auction.
- Check all the places should show all the data in the tables.
---
> Fix: Media Container Size showing undefined in the table.

- .github/workflows/tests-unit-js.yml
This is a LSC run by http://go/ghss to upgrade all depreacated ubuntu-20.04 runners to ubuntu-24.04.
On April 1, 2025, GitHub will stop supporting ubuntu-20.04 runners and workflows configured with this label will cease to run.  This PR is an attempt to save you work by doing the upgrade for you.
WARNING: We do not know if the updated label is compatiable with your workflow or not.
If you do not want to merge this PR, feel free to close it and deal with the problem yourselves.
More context and feedback: http://b/406537467
> Update runners to ubuntu-24.04 from deprecated ubuntu-20.04 label

- bin/install.sh
Add new line before appending script into bash file
I had problems installing the CLI in my machine and kept getting a error: `.zshrc:51: parse error near 'then'` due to the script not addding a new line.
- Pull branch `fix/cli-install`
- Run install locally `sh bin/install.sh`
- CLI commands get install succesfuly
- [NA] This code is covered by unit tests to verify that it works as intended.
> Fix: CLI install script

- packages/design-system/src/components/jsonView/jsonView.css
- packages/design-system/src/components/jsonView/jsonView.tsx
- packages/extension/src/view/devtools/app.tsx
- packages/extension/src/view/devtools/index.tsx
- packages/extension/src/view/devtools/tests/app.tsx
Apply dynamic dark/light mode when changing broswer's appearance theme
1. Pull and checkout the branch `enhancement/dynamic-dark-mode`
4. Go to`chrome://settings/appearance` 
5. Select a different appearance theme mode
6. Observe: the PSAT extension swaps theme mode automatically
> Enhancement: Dynamic dark mode

- packages/extension/src/view/devtools/pages/privateAdvertising/topics/explorableExplanation/panel.tsx
This PR fixes incorrect access counts by resetting the topics table data for an epoch if it was not completed in the first render.
- Open PSAT and navigate to topics EE.
- Let the animation run for a bit, then click on any topic in the table, and this should open the tax tree.
- Now come back to the EE tab, the access count should be correct.
- Now resize the table tray, and the data should remain correct.
---
Fixes #
> Fix: Incorrect access count in topics EE

- packages/extension/src/view/devtools/pages/settings/components/informationContainer.tsx
Add padding in settings container
1. Pull and checkout the branch `improvement/initial-theme-mode`
4. Open settings page
5. Observe: the settings containers have padding
- Before
- After
> Fix: Settings container padding

- packages/explorable-explanations/src/protectedAudience/modules/auctions/index.ts
- packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/explorableExplanation/index.tsx
- packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/panel.tsx
The notification bubble on the Ad Unit tab disappears the first time the IG demo is run under Protected Audience. This PR resolves the issue by relocating the unhighlighting logic to the onCommitted listener. This ensures the tab’s highlight is correctly reset when data disappears during a page reload.
- Open PSAT and navigate to https://privacysandboxdemos.domain-aaa.com/
- Select multi-auction demo.
- Add some IGs from both advertisers and run an auction.
- The adunits tab notification bubble does not disappear.
- Now compare to the release branch, where the bubble disappears on first auction run.
---
Fixes #
> Fix: Ad unit tab notification bubble disappearance

- packages/explorable-explanations/src/protectedAudience/modules/auctions/multi-seller/setUpComponentAuctions.ts
- packages/explorable-explanations/src/protectedAudience/modules/auctions/setupShowWinningAd.ts
- packages/explorable-explanations/src/protectedAudience/utils/scrollToCircle.ts
Fixes scrolling when animation is paused
Never scroll if the autoscroll is disable or animation paused
1. Pull and checkout the branch `fix/paused-scrolling`
4. Go PA:EE
5. Enable auto scroll
6. Wait for a winning app to show up
7. Pause the animation
8. Observer, the animation doesn't trigger any scrolling
https://github.com/user-attachments/assets/25f12ba2-aae0-4353-bde0-38269f7d8c76
> Fix: Prevent auto scrolling when animation is paused in EE

- packages/explorable-explanations/src/protectedAudience/config.ts
- packages/explorable-explanations/src/protectedAudience/modules/auctions/multi-seller/setUpComponentAuctions.ts
- packages/explorable-explanations/src/protectedAudience/modules/auctions/multi-seller/setUpFirstSSPTagFlow.ts
- packages/explorable-explanations/src/protectedAudience/modules/auctions/multi-seller/setUpPublisherAdServerFlow.ts
- packages/explorable-explanations/src/protectedAudience/modules/auctions/setUpRunadAuction.ts
- packages/explorable-explanations/src/protectedAudience/modules/auctions/single-seller/setupFirstSSPTagFlow.ts
- packages/explorable-explanations/src/protectedAudience/modules/flowConfig.tsx
- packages/explorable-explanations/src/protectedAudience/modules/joinInterestGroup.ts
- packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/explorableExplanation/tableTabPanels/legend.tsx
- This PR updates the flow diagrams to use yellow-colored boxes for steps where SSPs are required to make minimal changes, as outlined in the Protected Audience API SSP integration guide. The color change visually distinguishes low-effort implementation steps to help developers quickly identify them in the integration workflow. 
- It also removes yellow color for the non browser boxes and updates the legend to reflect these changes.
- Go to EE PA and check if all SSP boxes have yellow color.
- Legend doesn't have any typos.
---
Fixes #
> Update diagram boxes to yellow for SSPs with minimal integration changes

- packages/explorable-explanations/src/protectedAudience/components/progressLine.ts
- packages/explorable-explanations/src/protectedAudience/modules/auctions/multi-seller/setUpFirstSSPTagFlow.ts
- packages/explorable-explanations/src/protectedAudience/modules/auctions/single-seller/setupFirstSSPTagFlow.ts
- packages/explorable-explanations/src/protectedAudience/modules/joinInterestGroup.ts
This PR adds a textual description to arrows to attribute their role in the PA EE flow.
- Adds `Tagging call` text to the arrow from DSP tags to DSPs in the advertiser flow.
- Adds `Ad Request` text to the arrow from SSP adapter to SSP, `OpenRTB bid request` from SSP to DSPs, and `OpenRTB bid response` from DSPs to SSP in the publisher flow.
- It also changes the positioning of text around up and down arrows by using `textWidth` function.
- Open PSAT and navigate to PA EE.
- Run the flow, the arrow from DSP tags to DSPs in the advertiser flow should have `Tagging call` text.
- In publisher flow, `Ad Request` text to the arrow from SSP adapter to SSP, `OpenRTB bid request` from SSP to DSPs, and `OpenRTB bid response` from DSPs to SSP
---
- ~This code is covered by unit tests to verify that …
> Enhancement: Add textual description to PA EE arrows

- packages/extension/src/view/devtools/pages/layout.tsx
Only display icon buttons in smaller screens
1. Pull and checkout the branch `fix/setting-warning-buttons`
4. Go to settings
5. Enable CPD
6. Observe the buttons on the toast message have icons only when the buttons are large
-Large screen
-Small screen
> Fix: Show CDP settings icon buttons only in smaller screens

- packages/design-system/src/components/landingPage/cardsPanel.tsx
- packages/design-system/src/components/landingPage/contentPanel.tsx
- Improve cads UI by adding better contrast in the border, adding color and slightly increasing border width
1. Pull and checkout the branch `fix/cards-borders`
4. Go any landing page that contains cards: Dashboard, Learning, Tracking Protection, Private Advertising, Site Boundaries
5. Observe that the cards have a colored border and they look consistent in all pages
- Light theme:
- Dark theme:
- [NA] This code is covered by unit tests to verify that it works as intended.
> Fix: Panel cards borders

- packages/extension/src/view/devtools/pages/dashboard/constants.ts
Add demo button in learning card
1. Pull and checkout the branch `fix/learning-card`
4. Go to Dashboard
5. Observer the learning card has a link to the demos
> Fix: Learning card demo link

- package-lock.json
- packages/design-system/src/components/timeline/bar.tsx
- packages/design-system/src/components/timeline/index.tsx
This PR updates the logic to handle overlapping of texts, lines in the timeline.
Also, it updates the width for the timeline container, such that there's no unnecessary space to the right when zoomed.
- Open PSAT and navigate to the bids timeline.
- Find a site where the auction, timeout timings are close by.
- Check that the gap between texts is enough not to overlap.
- Now find a scenario where values are similar to block lines.
- The text position should be adjusted so that it doesn't overlap the line.
---
Fixes #
> Fix: Update text and line position calculation in timeline

- packages/design-system/src/components/table/components/tableHeader/headerCell.tsx
- packages/design-system/src/components/table/useTable/useColumnResizing/index.tsx
- packages/extension/src/view/devtools/pages/privacyProtection/ipProtection/mdlTable/index.tsx
Fixes and issue in the tables where the initialWith is not respected
remove the logic from the react component and moved all logic to the resize hook to improve readibility
1. Pull and checkout the branch `fix/table-column-initialwidth`
4. Delete any Extension Storage (DevTools -> Application)
5. Go to Marked Domain LIst table in IP protection
6. Observe, the inital width of 100px is respected for the columns
- Before
- After
---
- [NA] This code is covered by unit tests to verify that it works as intended.
> Fix: Table column initial width

- package-lock.json
- package.json
- packages/design-system/src/components/sidebar/useSidebar/provider.tsx
- packages/extension/src/view/devtools/stateProviders/settings/settingsProvider.tsx
- tests/shared.jest.config.cjs
This PR addresses two separate issues:
1.  It refactors the browser version detection logic to use the more modern and reliable User-Agent Client Hints API (`navigator.userAgentData`) instead of parsing the user-agent string. A fallback to the old method is retained for browsers that don't support the new API.
2.  It fixes a bug in the sidebar's keyboard navigation where `event.preventDefault()` was being called too broadly, interfering with default browser actions like activating a link with the 'Enter' key.
---
* **Browser Version Detection**: The component now first attempts to use `navigator.userAgentData.getHighEntropyValues(['fullVersionList'])` to retrieve detailed browser and platform information. This approach is preferred as user-agent strings are becoming less reliable. If this …
> Fix: Chrome version number and fix focus after sidebar use
