README.md
=> Changed inisghts to insights

.gitignore, package.json, tests/jest.config.js
Add configuration to generate and view test coverage report.
=> Chore: Setup test coverage report

packages/extension/src/view/devtools/components/tabContent/cookies/cookiesListing/cookieTable/index.tsx, packages/extension/src/view/devtools/stateProviders/filterManagementStore/constants.ts, packages/extension/src/view/devtools/stateProviders/filterManagementStore/utils/filterCookies.ts, packages/extension/src/view/devtools/stateProviders/filterManagementStore/utils/getFilters.ts
Update the third-party filter label to scope in the cookies tab.
- Create another constant for handling all custom filters.
- Refactor code.
- Update label in table columns too.
---
Fixes #
=> Update third party filter label to scope

packages/extension/src/view/design-system/components/circle/index.tsx, packages/extension/src/view/design-system/components/circlePieChart/emptyCirclePieChart.tsx, packages/extension/src/view/design-system/components/circlePieChart/index.tsx, packages/extension/src/view/design-system/components/matrix/matrixComponent/matrixComponentHorizontal.tsx, packages/extension/src/view/devtools/components/tabContent/cookies/cookiesLanding/landingHeader/index.tsx
Fix cookies landing pages raised during the QA of the extension.
- Fix hidden circles
- Set minimum width to horizontal matrix counts
- Update matrix count color
- Fix partitioned empty circle in dark mode.
---
Fixes #
=> Fix: Cookies landing page issues

packages/extension/src/view/design-system/components/circlePieChart/emptyCirclePieChart.tsx, packages/extension/src/view/design-system/components/circlePieChart/index.tsx, packages/extension/src/view/design-system/components/circlePieChart/stories/circlePieChart.stories.tsx, packages/extension/src/view/design-system/components/circlePieChart/stories/emptyCirclePieChart.stories.tsx, packages/extension/src/view/design-system/components/circlePieChart/tests/circlePieChart.tsx, packages/extension/src/view/popup/app.tsx, packages/extension/src/view/popup/stateProviders/syncCookieStore/index.tsx, packages/extension/src/view/popup/tests/index.tsx
This PR updates popup's `loading` state's timeout and adds loading text in UI.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/58820001/74c9f554-662a-4c97-a533-6532f88d544b
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/58820001/a33acf30-2904-4a43-a0f5-c1f436ab04df
---
Fixes #
=> Update popup loading state

packages/extension/src/view/devtools/components/tabContent/cookies/cookiesLanding/cookiesMatrix/index.tsx, packages/extension/src/view/devtools/components/tabContent/cookies/cookiesLanding/cookiesMatrix/tests/cookieMatrix.tsx, packages/extension/src/view/devtools/stateProviders/filterManagementStore/constants.ts, packages/extension/src/view/devtools/stateProviders/filterManagementStore/utils/filterCookiesWithRetentionPeriod.ts, packages/extension/src/view/devtools/stateProviders/filterManagementStore/utils/tests/filterCookies.ts, packages/extension/src/view/devtools/stateProviders/filterManagementStore/utils/tests/filterCookiesWithRetentionPeriod.ts
This PR adds an additional "platform" filter, renames the retention period, and updates the matrix text to insights.
---
Fixes #
=> Add platform filter and minor text updates.

README.md
=> Readme: Update the broken downloadable link and fix typos.

packages/cli/src/index.ts, packages/cli/src/types.ts, packages/cli/src/utils/generatePrefix.ts, packages/cli/src/utils/generateTechnology.ts, packages/cli/src/utils/normalizeCookies.ts
Improves CSV output of the CLI tool by adding Url column and adding a user-defined prefix to the output files.
---
Fixes #
=> Improvements in the CLI output

packages/extension/src/view/devtools/components/cookies/cookiesLanding/cookiesMatrix/index.tsx
Enhance the text describing the different categories of cookies in the Expanded View of the Cookies Matrix.
=> Enhance descriptions in Expanded View Cookie Matrix

packages/common/src/cookies.types.ts, packages/extension/src/contentScript/popovers/tooltip/createTooltip.ts, packages/extension/src/contentScript/types.ts, packages/extension/src/localStore/tests/cookieStore.ts, packages/extension/src/view/devtools/app.tsx, packages/extension/src/view/devtools/components/sidebar/tests/index.tsx, packages/extension/src/view/devtools/devtools.ts, packages/extension/src/view/devtools/hooks/useFrameOverlay.ts, packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx, packages/extension/src/view/devtools/tests/app.tsx, packages/extension/src/view/devtools/tests/index.tsx
This PR aims to add if the frame belongs to RWS.
- Gather if frame belongs to RWS while collecting frames of a tab.
---
=> Feature: Add data if frame belongs to RWS

packages/design-system/src/components/table/table.tsx, packages/design-system/src/components/table/tableBody/bodyCell.tsx, packages/design-system/src/components/table/tableBody/index.tsx, packages/design-system/src/components/table/tableHeader/headerCell.tsx, packages/design-system/src/components/table/useColumnResizing/index.tsx, packages/extension/src/view/devtools/app.tsx, packages/extension/src/view/devtools/components/cookies/tests/cookieTab.tsx
This PR makes changes to table UI/UX wrt to resizing columns as table container size changes.
---
Fixes #
=> Update table UI

packages/design-system/src/components/landingPage/constants.ts, packages/extension/src/view/devtools/components/privacySandbox/index.tsx
Reuse `LandingPage` component on Privacy Sandbox page used on other landing pages.
---
Fixes #
=> PS landing page improvements

packages/design-system/src/components/bulletList/listRow.tsx, packages/design-system/src/components/cookieTable/index.tsx, packages/design-system/src/components/landingPage/index.tsx, packages/design-system/src/components/table/table.tsx, packages/design-system/src/components/table/tableHeader/headerCell.tsx, packages/extension/src/view/devtools/components/antiCovertTracking/antiCovertTracking.tsx, packages/extension/src/view/devtools/components/antiCovertTracking/bounceTracking/index.tsx, packages/extension/src/view/devtools/components/antiCovertTracking/fingerprinting/index.tsx, packages/extension/src/view/devtools/components/privacySandbox/index.tsx, packages/extension/src/view/devtools/components/privateAdvertising/attribution/index.tsx, packages/extension/src/view/devtools/components/privateAdvertising/privateAdvertising.tsx, packages/extension/src/view/devtools/components/privateAdvertising/topics/index.tsx, packages/extension/src/view/devtools/components/privateAdvertising/topics/topicsList.tsx, packages/extension/src/view/devtools/components/siteBoundaries/chips/index.tsx, packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/index.tsx, packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/index.tsx, packages/extension/src/view/devtools/components/siteBoundaries/siteBoundaries.tsx
This PR updates styling of UI elements for better responsiveness, user experience, and visual appeal. 
---
Fixes #
=> Update styling of UI elements

packages/design-system/src/components/accordion/accordionChildren.tsx, packages/extension/src/view/devtools/components/sidebar/index.tsx, packages/extension/src/view/devtools/components/sidebar/keyboardNavigationHandlers/arrowDownHandler.ts, packages/extension/src/view/devtools/components/sidebar/keyboardNavigationHandlers/arrowUpHandler.ts
This PR fixes the keyboard navigation of the sidebar not being consistent at times.
---
Fixes #
=> Fix: Update `Sidebar` navigation conditions and props

packages/design-system/src/@types/index.d.ts, packages/design-system/src/components/landingPage/index.tsx, packages/design-system/src/components/table/columnMenu/index.tsx, packages/extension/src/view/design-system/components/infoCard/learnMoreDropdown.tsx, packages/extension/src/view/design-system/components/infoCard/tests/infoCard.test.tsx, packages/extension/src/view/devtools/components/antiCovertTracking/antiCovertTracking.tsx, packages/extension/src/view/devtools/components/privacySandbox/index.tsx, packages/extension/src/view/devtools/components/privateAdvertising/privateAdvertising.tsx, packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/index.tsx, packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/insights/index.tsx, packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/index.tsx, packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/useGeneratorForm/index.tsx, packages/extension/src/view/devtools/components/siteBoundaries/siteBoundaries.tsx
This PR makes UI/UX changes to landing pages.
- Remove “Learn more” and “Close” button and show its content in default state.
- Create two sections for RWS Membership check; and (2) Generate RWS JSON Resources
- RSS feed items should be sorted by date order 
---
Fixes #
=> Update landing page's UI/UX

packages/extension/src/contentScript/index.ts, packages/extension/src/contentScript/popovers/tooltip/setTooltipPosition.ts
Reverts GoogleChromeLabs/ps-analysis-tool#201
=> Revert "Fix: Frame overlay issues"

packages/cli-dashboard/src/components/siteMapReport/index.tsx, packages/cli-dashboard/src/components/siteReport/components/layout.tsx, packages/cli-dashboard/src/components/siteReport/components/sidebar.tsx, packages/cli-dashboard/src/components/siteReport/components/siteSelection.tsx, packages/cli-dashboard/src/components/siteReport/stateProviders/contentStore/index.tsx, packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesLandingContainer/index.tsx, packages/cli-dashboard/src/components/siteReport/tabs/cookies/index.tsx, packages/cli/src/utils/browserManagement/index.ts, packages/common/src/index.ts
This PR makes styling changes to the sidebar item's padding and updates `Unknown Frame` to `Unknown Frame(s)`.
---
Fixes #
=> Update sidebar items padding and make `Unknown Frame` plural

CHANGELOG.md, package-lock.json, package.json, packages/cli/package.json, packages/common/package.json, packages/design-system/package.json, packages/eslint-import-resolver/package.json, packages/extension/package.json, packages/extension/src/manifest.json
=> Bump version to 0.3.1 and add changelog

packages/cli/src/procedures/analyzeCookieUrls.ts, packages/cli/src/utils/browserManagement/types.ts
CLI dashboard had missing descriptions for cookies in open cookie database. This PR fixes that.
---
Fixes #
=> Fix : Add missing description in analytics

bin/chrome_launcher.sh
Updating extension version
This pull request adds the latest extension version
pumping the version to download the current version v 0.3.2
---
Fixes #
=> Update extension version onchrome_launcher.sh

packages/design-system/src/components/landingPage/constants.ts
This PR updates the order and adds new items to Quick links on landing pages.
---
Fixes #328
=> Update quick links on landing pages

packages/common/src/cookies.types.ts
Fixes build routine of CLI by adding the missing type CookieDatabase
=> Fix: Add missing type in common package

packages/cli-dashboard/src/components/affectedCookies/index.tsx, packages/cli-dashboard/src/components/siteMapReport/index.tsx, packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesListing/index.tsx, packages/cli-dashboard/src/components/siteReport/tabs/cookies/index.tsx, packages/cli-dashboard/src/components/siteReport/tabs/siteAffectedCookies/index.tsx, packages/cli-dashboard/src/components/utils/reshapeCookies.ts, packages/cli-dashboard/src/components/utils/tests/reshapeCookies.ts, packages/common/src/cookies.types.ts, packages/design-system/src/components/cookiesLanding/cookiesMatrix/stories/cookiesMatrix.stories.tsx, packages/design-system/src/components/sidebar/sidebarChild.tsx, packages/design-system/src/components/table/components/filtersSidebar/chips/index.tsx, packages/design-system/src/components/table/components/index.tsx, packages/design-system/src/components/table/useTable/index.tsx, packages/design-system/src/components/table/useTable/useFiltering/index.tsx, packages/extension/src/utils/test-data/frameFilteredCookies.ts, packages/extension/src/view/devtools/components/cookies/cookiesListing/index.tsx, packages/extension/src/view/popup/tests/index.tsx
This PR fixes the following bugs. 
- CLI dashboard not showing count on the dashboard when analyzing sitemaps
- Affected cookies showing up ( the columns are highlighted so there is no need for that column )
- Every cookie in affected cookies is highlighted in the affected cookies table. 
- Filter disappears once you click on the filter option for which the cookie is not present.
- Missing padding from top and bottom when the single filter is applied.
- The cookie icon shows a white color when unfocused.
- Add Priority and Size filters.
Partially addresses #339
=> Fix: Regression testing for 0.4 release.

packages/common/src/cookies.types.ts, packages/common/src/utils/parseRequestWillBeSentExtraInfo.ts, packages/common/src/utils/parseResponseReceivedExtraInfo.ts, packages/extension/src/contentScript/index.ts, packages/extension/src/serviceWorker/index.ts, packages/extension/src/view/devtools/components/cookies/cookiesListing/index.tsx, packages/extension/src/view/devtools/hooks/useFrameOverlay.ts, packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
This PR fixes the frame overlay button not being visible and disabling the cookie deletion button when no cookie is selected.
---
Partially addresses #339
=> Fix: Issues generated in regression testing for 0.4 release.

packages/extension/src/serviceWorker/index.ts
This PR adds fixes to the below-listed bugs
- The URL is not working as expected. rewriting the URL does not load the correct set of cookies within some expected set of time and takes longer than expected.
- Only Top frame shows the cookies. And rest frames are blank.
- Filtered options does not persist everytime.
---
Partially addresses #339
=> Refactor: Update promise queue management in service worker

packages/extension/src/view/settings/components/tabContent/information/index.tsx, packages/extension/src/view/settings/stateProviders/syncSettingsStore/constants.ts, packages/extension/src/view/settings/stateProviders/syncSettingsStore/index.tsx
This PR adds an enum to handle converting Chrome type to full string and updates the formating of info being shown.
---
=> Refactor: Update Chrome and OS info format

.github/PULL_REQUEST_TEMPLATE.md
Add a checklist to the PR template
---
Fixes #
=> Add new checklist to the PR template

packages/design-system/src/components/cookiesLanding/cookiesMatrix/index.tsx, packages/design-system/src/components/searchInput/index.tsx, packages/design-system/src/components/table/components/tableTopBar/index.tsx, packages/extension/src/view/devtools/components/cookies/cookiesListing/index.tsx, tailwind.config.cjs
This PR aims to implement a few UI changes requested
- Update the frame's horizontal matrix description.
- Make the table top-bar bg color consistent with the Application tab.
- Put Unknown platform if not available in devtools.
---
Fixes #297 #298 #319
=> Fix: Update minor UI elements

packages/design-system/src/utils/prepareFrameStatsComponent.ts
This reverts commit 70308634c19720263e75c04c8efffb424b19af1e.
---
Fixes #
=> Revert "Adding plural string for "Frame details" sections (#382)"

bin/chrome-3pcd-ps.bat, bin/chrome-default-ps.bat, bin/chrome_launcher.sh
Update PSAT extension version to v0.4.1 for quick launcher CLI
---
Fixes #
=> Update PSAT extension version to v0.4.1 for quick launcher CLI

.github/PULL_REQUEST_TEMPLATE.md
Reverts GoogleChromeLabs/ps-analysis-tool#370
=> Revert "Add new checklist to the PR template"

packages/common/src/utils/calculateEffectiveExpiryDate.ts, packages/common/src/utils/parseRequestWillBeSentExtraInfo.ts, packages/common/src/utils/parseResponseReceivedExtraInfo.ts, packages/design-system/src/components/sidebar/useSidebar/index.tsx, packages/design-system/src/utils/prepareFrameStatsComponent.ts, packages/extension/src/localStore/utils/updateCookieBadgeText.ts, packages/extension/src/serviceWorker/index.ts, packages/extension/src/view/devtools/components/cookies/cookiesListing/index.tsx, packages/extension/src/view/devtools/components/cookies/index.tsx, packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
Add missing docs and todos
---
Fixes #
=> Chore: Add missing docs and todos

README.md, data/PSInfo.json, packages/extension/src/serviceWorker/index.ts
developer.chrome.com was migrated to new infrastructure and the PS is on its own site. Most of the links still work thanks to redirects (though not eh [FLEDGE one](https://developer.chrome.com/docs/privacy-sandbox/fledge-api/) - corrected in this PR) but still, best to point them to the right place.
Test the old URLs redirect to the new ones.
---
Fixes #
=> Update d.c.c. links

third_party/data/open-cookie-database.json
Update cookie database from the fork of [Open-Cookie-Database](https://github.com/rtCamp/Open-Cookie-Database) from https://github.com/rtCamp/Open-Cookie-Database
---
Fixes #
=> Chore: Update cookie database

data/related_website_sets.json
Update RWS data from [related_website_sets.JSON](https://github.com/GoogleChrome/related-website-sets/blob/main/related_website_sets.JSON)
---
Fixes #
=> Chore: Update related website sets data

packages/extension/src/view/devtools/components/cookies/cookiesListing/index.tsx
This PR adds `Partition Key` filter in the extension and make changes to Blocked Reasons.
---
Fixes #
=> Enhancement: Add `Partition Key` filter to extension

packages/extension/src/serviceWorker/index.ts, packages/extension/src/store/synchnorousCookieStore.ts, packages/extension/src/store/utils/updateCookieBadgeText.ts
This PR aims to fix the zero cookie issue when the window is reopened without closing it properly.
---
Partially addresses #471
=> Fix: Zero cookie issue when window is reopened.

packages/library-detection/src/libraries/gsi/accordion.tsx
=> Nit: remove unneeded word

packages/extension/src/view/devtools/app.tsx, packages/extension/src/view/popup/app.tsx
This PR aims to fix the UI and change the messaging in the toast message as suggested.
---
=> Fix: UI and change messaging in toast message

packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/useHighlighting.tsx
Reverts GoogleChromeLabs/ps-analysis-tool#518 in favour of https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/531
=> Revert "Fix: Allow listed rows to highlight after frame change"

packages/design-system/src/components/toastMessage/index.tsx, packages/extension/src/view/devtools/app.tsx, packages/extension/src/view/devtools/components/settings/components/informationContainer.tsx, packages/extension/src/view/devtools/components/settings/components/tests/informationContainer.tsx, packages/extension/src/view/devtools/stateProviders/syncSettingsStore/index.tsx
This PR updates the UI and some logic on the settings page.
- Fixes `ToastMessage` width to remain stretched across the div even when the sibling element is overflowing.
- Add the PSAT version to the settings page.
- Update the copying of information to markdown format.
- Open the settings page, and click on the enable CDP button.
- Try to resize the settings page, the toast message will appear spread across the page width.
- On the Information tab, a new heading will be available named PSAT version.
- Click on copy icon, and open an markdown editor, the copied text will reflect the copied content.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/58820001/f98efeae-944a-4c02-8586-aa01ff57f39a
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/58820001/32c82d3c-d03a-47c8- …
=> Miscellaneous settings page changes

packages/cli-dashboard/src/components/siteMapReport/sidebarData.ts, packages/cli-dashboard/src/components/siteReport/tabs/index.ts, packages/cli-dashboard/src/components/utils/reportDownloader/utils.ts, packages/cli/src/utils/saveCSVReports.ts, packages/design-system/src/components/sidebar/useSidebar/constants.ts
CLI, replace "Cookies with issues" with "Cookie issues" in the sidebar.
=> Enhancement: CLI, replace "Cookies with issues" with "Cookie issues" in the sidebar.

packages/cli-dashboard/src/components/utils/reportDownloader/generateSiteMapReportandDownload.ts, packages/cli-dashboard/src/components/utils/reportDownloader/generateSiteReportandDownload.ts, packages/cli-dashboard/src/components/utils/reportDownloader/utils.ts, packages/cli/src/index.ts, packages/cli/src/utils/validateArgs.ts
This PR do the following fixes.
- Remove “Provided dir....” message to make it shorter.
- Change “report” to the format - psat_cli_report_cnn-com_04102028 for cli exports.
- Replace: "Report is being served at the URL: <url>" Report: <url>
=> Enhancement: CLI updates

packages/cli/src/utils/browserManagement/index.ts
Removes debug log statement from invalid context. This was causing accept banner action to fail.
Fixes #
=> Fix: Remove debug log statement

packages/design-system/src/components/index.ts, packages/design-system/src/components/landingPage/contentPanel.tsx, packages/extension/src/view/devtools/components/antiCovertTracking/antiCovertTracking.tsx, packages/extension/src/view/devtools/components/layout.tsx, packages/extension/src/view/devtools/components/privateAdvertising/privateAdvertising.tsx, packages/extension/src/view/devtools/components/siteBoundaries/siteBoundaries.tsx
This PR adds code for updating the UI for the landing page with new content and styles.
- Clone this branch and build the extension.
- Open PSAT panel and click on Site boundaries landing page.
- The page should open with 4 tiles showing new content.
- Click on any tile will open new page with docs related to the topic clicked.
- Try same Tracking protection and Private advertising landing pages.
- 
---
Fixes #
=> Update landing pages UI

packages/cli-dashboard/src/components/cookiesWithIssues/index.tsx, packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesLandingContainer/cookieLanding/blockedCookiesSection.tsx, packages/cli-dashboard/src/components/siteReport/tabs/index.ts, packages/design-system/src/components/cookiesLanding/useFiltersMapping.tsx
This PR adds code to
- Highlight rows of the `CookieIssues` table.
- Add click event on categories section under Blocked reasons matrix
- Analyze a site from CLI and open the dashboard.
- Open the cookie landing page and scroll to the blocked reasons section
- There will be a category matrix, click on any item.
- It will open the cookie table on the first frame with filters selected.
- Now open the cookie issues table, the rows should be highlighted.
https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/58820001/57464389-34cf-45c7-9c08-5933751209a7
---
Fixes #
=> Miscellaneous CLI dashboard changes

bin/install.sh
=> Fetch Chrome launcher script from `main` instead of `develop` branch

packages/extension/src/contentScript/index.ts, packages/extension/src/view/devtools/hooks/useFrameOverlay.ts
This PR aims to fix the errors that appear on the extensions page.
- Go to the terminal and run `npm start`
- Open any website and click on the frame overlay icon.
- Now switch the tab you should not see an error on the extensions page anymore.
---
=> Fix: Errors appearing on extension page

data/related_website_sets.json
Update RWS data from [related_website_sets.JSON](https://github.com/GoogleChrome/related-website-sets/blob/main/related_website_sets.JSON)
---
Fixes #
=> Update RWS JSON before release

package-lock.json, package.json
The Storybook package has been found to contain four high-severity vulnerabilities. As Storybook is not currently a hard dependency for PSAT, we're temporarily removing Storybook package dependencies from package.json. This will be in place until the issues are fixed in an upcoming Storybook version or we find a solution.
- Run `npm audit report`.
- It should show `found 0 vulnerabilities`
---
- ~[ ] The QA of this PR is done by a member of the QA team (to be checked by QA).~ NA
Fixes #701
=> Temporarily remove storybook package

package-lock.json
Run `npm audit fix` to fix braces vulnerability
=> Run audit fix for braces package vulnerability

packages/analysis-utils/src/procedures/analyzeCookiesUrlsInBatchesAndFetchResources.ts, packages/analysis-utils/src/procedures/analyzeTechnologiesUrlsInBatches.ts, packages/cli/src/index.ts, packages/cli/src/utils/getUrlListFromArgs.ts, packages/cli/src/utils/getUrlsfromSitemap.ts, packages/cli/src/utils/validateArgs.ts
This PR aims to improve the CLI output messages to be more concise.
---
- ~~[ ] The QA of this PR is done by a member of the QA team (to be checked by QA).~~
=> Feature: Smaller and concise CLI messaging

package-lock.json, package.json
The current version of Wappalyzer used in this project uses an outdated version of Puppeteer. This PR overrides. it to the latest version.
- Audit any website to test if technologies are being analayzed as expected.
- There should be 0 vulnerabilities when running `npm audit report`.
---
Fixes #
=> Fix Wappalyzer vulnerability issue

packages/design-system/src/components/table/utils/generateCLICookieTableCSV.ts, packages/i18n/src/i18n.ts, packages/i18n/src/tests/i18n.ts, webpack.shared.cjs
This package aims to resolve the path and fix the same site values in CLI generated cookie table csv.
---
=> Fix: Samesite value in cookie table CSV.

packages/design-system/src/components/menuBar/index.tsx, packages/design-system/src/components/table/useTable/useColumnSorting/index.tsx, packages/extension/src/view/devtools/components/cookies/cookieLanding/landing.tsx
This PR fixes
- [On the page where no cookies are present, the report button is enabled, but the report download button is not working properly.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2244389403)
- [The horizontal scroller should appear when multiple filters are selected in the global filter. Also, the menu bar could be positioned a bit lower. ](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2244742229)
- [The path column sorting filter is not working properly. The column has only one value, but when clicking on the filter, the values are changing.](https://github.com/GoogleChromeLabs/ps-analysis-tool/issues/768#issuecomment-2249606488)
- Open URL https://domain-aaa.com/facebook-like in browser.
- Open PSAT Panel inside …
=> Fix: QA issues on develop

package-lock.json, packages/cli-dashboard/package.json, packages/cli/package.json, packages/common/package.json, packages/design-system/package.json, packages/eslint-import-resolver/package.json, packages/i18n/package.json, packages/library-detection/package.json, packages/report/package.json
Increase the CLI and its package dependency versions to do a minor path release after the README text update in https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/839
NA
---
Fixes #
=> Bump CLI version for minor patch release

packages/extension/src/contentScript/types.ts, packages/extension/src/contentScript/utils/getTooltipInfoData.ts, packages/extension/src/view/devtools/hooks/useFrameOverlay.ts
=> Fix typo for `numberOfBidders`

packages/explorable-explanations/src/components/box.js, packages/explorable-explanations/src/components/branches.js, packages/explorable-explanations/src/components/index.js, packages/explorable-explanations/src/components/rippleEffect.js, packages/explorable-explanations/src/config.js, packages/explorable-explanations/src/modules/auctions.js
This PR creates ripple effect component and add support for description in box component and add details to auction flow
---
- ~[ ] The QA of this PR is done by a member of the QA team (to be checked by QA).~
=> Create ripple effect component and add description to box component

package-lock.json
This PR addresses vulnerabilities reported in the dependency audit for the repository.
- 	The vulnerability in validate.js remains unresolved as no fix is currently available ([link to advisory](https://github.com/advisories/GHSA-rv73-9c8w-jp4c)).
**Next Steps**
-  Explore alternatives to validate.js.
- Monitor for updates or patches to address this issue.
=> Address package vulnerabilities and dependency updates

package-lock.json, packages/extension/package.json, packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/utils/validateContactEmail.ts, packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/utils/validateRationale.ts, packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/utils/validateUrl.ts
This PR aims to remove validator.js library to fix the vulnerability.
- Instead of using the library we are now using our custom validators.
---
~~- [ ] The QA of this PR is done by a member of the QA team (to be checked by QA).~~
=> Remove validatejs and use custom validator.

packages/explorable-explanations/src/protectedAudience/index.js, packages/explorable-explanations/src/protectedAudience/modules/bubbles.js, packages/explorable-explanations/src/protectedAudience/modules/timeline.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/index.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseClickedInNonInteractiveModeCallback.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseMovedInInteractiveMode.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseMovedInNonInteractiveMode.js
This PR aims to resolve regression bugs in EE PA.
---
=> Fix: EE PA bugs

packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/adUnits/panel.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/auctions/index.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/bids/noBidsTable.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/bids/panel.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/bids/receivedBidsTable.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/evaluationEnvironment.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/tableTabPanels/auctions.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/interestGroups/index.tsx
This PR adds code to add an evaluation environment placeholder to PA tables.
https://github.com/user-attachments/assets/e848f189-1eeb-4d76-b927-662f325a8332
---
Fixes #785
=> Enhancement: Add Evaluation Environment text to PA tabs

packages/explorable-explanations/public/styles.css, packages/explorable-explanations/src/protectedAudience/app.js, packages/explorable-explanations/src/protectedAudience/components/box.js, packages/explorable-explanations/src/protectedAudience/components/branches.js, packages/explorable-explanations/src/protectedAudience/components/flowExpander.js, packages/explorable-explanations/src/protectedAudience/components/progressLine.js, packages/explorable-explanations/src/protectedAudience/index.js, packages/explorable-explanations/src/protectedAudience/modules/bubbles.js, packages/explorable-explanations/src/protectedAudience/utils/index.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseClickedInInteractiveModeCallback.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseClickedInNonInteractiveModeCallback.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseMovedInInteractiveMode.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseMovedInNonInteractiveMode.js, packages/explorable-explanations/src/protectedAudience/utils/scrollToCoordinates.js, packages/extension/src/view/devtools/app.css, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/panel.tsx
This PR aims to implement autoscrolling in the canvas. When the canvas drawing goes beyond viewport, the canvas automatically scrolls so that users can view the drawings.
- In the terminal run `npm i && npm run build:ext`.
- In the browser, go to example.com.
- Open DevTools and Open PSAT.
- The animation should be scrolling automatically.
---
~~- [ ] This code is covered by unit tests to verify that it works as intended.~~
Fixes #857
=> Feature: Auto scroll canvas for EE PA

packages/explorable-explanations/src/protectedAudience/modules/bubbles.js, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/index.tsx
This PR adds code that updates the highlighting and unhighlighting timing.
- Keep the latest selected bubble's related row in the IG table highlighted.
- Add a stroke to the selected bubble.
- Clear highlighting of row once bubble minimized.
https://github.com/user-attachments/assets/9fb9efb1-b95a-489a-9776-20392279d579
---
=> Enhancement: Update IG highlighting logic

packages/design-system/src/components/tabs/useTabs/provider.tsx, packages/explorable-explanations/src/protectedAudience/app.js, packages/explorable-explanations/src/protectedAudience/index.js, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/index.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/panel.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/tableTabPanels/auctions.tsx
This PR adds code that synchronizes tab highlighting as the data updates happen in the IG table, Auction table, and Bids table.
- Introduce new states that indicate changes in table data by deep comparison to the previous data state.
---
=> Feature: Sync tab highlighting with data

packages/explorable-explanations/src/protectedAudience/components/branches.js, packages/explorable-explanations/src/protectedAudience/index.js, packages/explorable-explanations/src/protectedAudience/modules/auctions/index.js, packages/explorable-explanations/src/protectedAudience/modules/flow.js, packages/explorable-explanations/src/protectedAudience/modules/joinInterestGroup.js, packages/explorable-explanations/src/protectedAudience/utils/drawOpenArrowWithoutAnimationIcon.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseClickedInInteractiveModeCallback.js, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseMovedInInteractiveMode.js, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/index.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/tableTabPanels/auctions.tsx
This PR aims to fix some bugs and issues discovered during the QA process of the EE in Protected Audience
- Clone this branch, build the extension.
- In example.com, go to DevTools and navigate to PSAT.
- In PSAT navigate to protected audience.
- In the EE check the following issues to be fixed.
Error checklist:
---
=> Fix: EE bugs

packages/explorable-explanations/src/protectedAudience/modules/auctions/multi-seller/setUpComponentAuctions.js, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/auctionEventTransformers.ts, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/explorableExplanation/index.tsx
This PR aims to fix regression in the develop branch.
- In the terminal run `npm i && npm run build:ext`.
- In the browser, go to example.com.
- Navigate to DevTools, go to PSAT extension and then navigate to Protected Audience tab.
- Now in the Explorable Explanations.
- In full speed check the following things.
Checklist:
- In advertiser the flow, try going to auction in the below table. It should not break.
- Check the multi-seller flow and then reload frame, it should not be buggy when starting.
- The multi-seller auction data should be seen in the table.
---
=> Fix: Regression in develop branch

packages/explorable-explanations/src/protectedAudience/components/branches.ts, packages/explorable-explanations/src/protectedAudience/config.ts, packages/explorable-explanations/src/protectedAudience/modules/auctions/multi-seller/setUpComponentAuctions.ts
This PR fixes the coordinates of auction flow branches.
---
Fixes #
=> Fix: Develop QA issues

packages/design-system/src/components/landingPage/LandingPage.tsx, packages/extension/src/view/devtools/components/antiCovertTracking/antiCovertTracking.tsx, packages/extension/src/view/devtools/components/privateAdvertising/privateAdvertising.tsx, packages/extension/src/view/devtools/components/siteBoundaries/siteBoundaries.tsx
Update all top-level Story URLs.
=> Update story urls

assets/amp/custom-scripts/amp-player-main.js, packages/extension/src/utils/getStaticStoryMarkup.ts
This PR aims to prettify the web stories section landing page of the PSAT extension.
- Removal of media queries
- Changing the height and width of the cards being displayed
- Conditional rendering of webstories publisher logo.
---
~~- [ ] This code is covered by unit tests to verify that it works as intended~~ NA
=> Make UI changes to web stories landing page.

packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/adUnits/panel.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/auctions/index.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/bids/noBidsTable.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/bids/receivedBidsTable.tsx, packages/extension/src/view/devtools/components/privateAdvertising/protectedAudience/evaluationEnvironment.tsx, packages/extension/src/view/devtools/tabs.ts
This PR makes the following UI Improvements.
- [Keep learning menu open by default](https://github.com/GoogleChromeLabs/ps-analysis-tool/commit/d62ac0dec3c146da24b92e3bb7a9d2b17d86574f)
- [Increase font size of evavluation env notice](https://github.com/GoogleChromeLabs/ps-analysis-tool/commit/39ba0d3555f7b2723487ee382fea1077ea79db68)
---
Fixes #
=> Small UI Improvements.

packages/design-system/src/components/sidebar/useSidebar/constants.ts, packages/extension/src/view/devtools/pages/dashboard/constants.ts, packages/extension/src/view/devtools/pages/learning/contentPanel.tsx, packages/extension/src/view/devtools/tabs.ts
This PR adds the recently added Learning box in the dashboard feature list.
---
- ~[ ] This code is covered by unit tests to verify that it works as intended~.
Fixes #
=> Feature: Add 'Learning' box in the dashboard feature list

packages/explorable-explanations/src/topics/index.ts, packages/extension/src/view/devtools/pages/privateAdvertising/topics/explorableExplanation/panel.tsx
This PR adds code to
- Add a slight delay before visiting the first node.
- The reset button shouldn't reset the speed.
- Fix bug - Already visited node appears in interactive mode after resetting
---
Fixes #856
=> Enhancement: Topics EE changes

packages/design-system/src/components/bulletList/listRow.tsx, packages/design-system/src/components/internalNavigationForAnchor/index.tsx, packages/design-system/src/components/landingPage/quickLinksList.tsx, packages/design-system/src/components/landingPage/supportLink.tsx, packages/extension/src/view/devtools/pages/cookies/cookieLanding/cookiesSection.tsx
This PR adds logic to open external URLs in the same tab.
https://github.com/user-attachments/assets/bbcb1e83-5477-4f65-9eec-83916c580809
---
=> Enhancement: Open links in same tab

packages/extension/src/view/devtools/pages/privateAdvertising/attributionReporting/panel.tsx
This PR adds code to update AR tabs with notification bubbles whenever data changes.
https://github.com/user-attachments/assets/92843595-d812-400e-bb58-aede748aea51
---
=> Feature: Add notification bubbles to ARA tabs

assets/amp/custom-scripts/amp-player-main.js, packages/explorable-explanations/src/protectedAudience/index.ts, packages/extension/src/contentScript/index.ts, packages/extension/src/serviceWorker/attachCDP.ts, packages/extension/src/serviceWorker/chromeListeners/syncStorageOnChangedListener.ts, packages/extension/src/serviceWorker/index.ts, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/auctions/table/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/topics/taxonomyTree/index.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/relatedWebsiteSets/jsonGenerator/utils/validateUrl.ts, packages/extension/src/view/devtools/stateProviders/protectedAudience/protectedAudienceProvider.tsx
This PR aims to fix develop issues.
- Scrolling of ad units is being done now using their top and left coordinates.
- Protocol matching is now changed, since protocol used to be `https` and `https:`.
- In the terminal run `npm run build:ext`
- Open a fresh profile and then go to `https://psat-pat-demos-shop.dev/items/1f45f?auctionType=multi`
- then in another tab open `https://psat-pat-demos-news.dev?auctionType=multi`.
- Now Go to ad Units section in the PA tab of DevTools.
- Click on ad unit to enable frame overlay, the ad should scroll into view.
- Now go to RWS JSON generator, ensure that domain is validated.
---
Fixes #
=> Fix: QA develop

packages/design-system/src/components/landingPage/LandingPage.tsx, packages/design-system/src/components/landingPage/index.tsx, packages/explorable-explanations/src/protectedAudience/canvas/setupInterestGroupCanvas.ts, packages/explorable-explanations/src/protectedAudience/canvas/setupMainCanvas.ts, packages/explorable-explanations/src/protectedAudience/canvas/setupUserCanvas.ts, packages/explorable-explanations/src/protectedAudience/index.ts, packages/explorable-explanations/src/protectedAudience/utils/increasePixelDensityConditionally.ts, packages/extension/src/view/devtools/pages/layout.tsx, packages/extension/src/view/devtools/pages/learning/demos/index.tsx, packages/extension/src/view/devtools/pages/learning/devSite/index.tsx, packages/extension/src/view/devtools/pages/learning/helpCenter/index.tsx, packages/extension/src/view/devtools/pages/learning/wiki/index.tsx, packages/extension/src/view/devtools/pages/privacyProtection/bounceTracking/index.tsx, packages/extension/src/view/devtools/pages/privacyProtection/ipProtection/index.tsx, packages/extension/src/view/devtools/pages/privacyProtection/privateStateTokens/index.tsx, packages/extension/src/view/devtools/pages/privacyProtection/userAgentReduction/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/privateAggregation/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/topics/explorableExplanation/animation.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/chips/index.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/federatedCredential/index.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/storageAccess/index.tsx
This PR fixes minor issues in the UI, which are listed below:
- When checking Frame overlay, the tab automatically switches to dashboard from cookies
- Fix regression of showing quick links and latest news in the footer of PA, Topics and ARA.
- Fix Landing page icons.
- Fix dark mode Topics EE and PA:EE
- Use semi-bold font weight for landing page card headings
---
~~- [ ] This code is covered by unit tests to verify that it works as intended.~~NA
=> Fix: Minor UI issues 

packages/design-system/src/components/menuBar/index.tsx
This PR fixes
- Inconsistent scroll behaviour on the cookie landing page
---
Fixes #
=> Fix: QA develop issues

packages/explorable-explanations/src/topics/index.ts
This PR fixes the inconsistent access count in the topics table while in interactive mode.
---
- ~This code is covered by unit tests to verify that it works as intended.
Fixes #
=> Fix: Calculate user visits conditionally

packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/auctions/panel/index.tsx, packages/extension/src/view/devtools/stateProviders/protectedAudience/protectedAudienceProvider.tsx, packages/extension/src/view/devtools/stateProviders/protectedAudience/utils/computeReceivedBidsAndNoBids.ts
This PR aims to solve the auction shaper to adapt to newer privacy sandcastle demos.
- Go to privacy sandcastle demos.
- In PSAT check that all the auction data should be populated.
---
~~ - [ ] This code is covered by unit tests to verify that it works as intended. ~~ NA
=> Fix: Refactor auction shaper

packages/explorable-explanations/src/protectedAudience/index.ts, packages/extension/src/contentScript/index.ts, packages/extension/src/manifest.json, packages/extension/src/serviceWorker/chromeListeners/onCommittedNavigationListener.ts, packages/extension/src/utils/getFramesForCurrentTab.ts, packages/extension/src/utils/processAndStoreDocumentCookies.ts, packages/extension/src/utils/tests/getFramesForCurrentTab.ts, packages/extension/src/view/devtools/pages/privateAdvertising/attributionReporting/utils/calculateRegistrationDate.ts, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/explorableExplanation/auctionEventTransformers.ts, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/interestGroups/table.tsx, packages/extension/src/view/devtools/stateProviders/cookie/cookieProvider.tsx, packages/extension/src/view/devtools/stateProviders/protectedAudience/protectedAudienceProvider.tsx
This PR aims to fix the following issues:
- Use uniform Date time format across extension (#1042)
- Detect JavaScript cookie across all the frames in the webpage.
- Some arrows in PA EE are left stranded when user clicks back or previous button during animation when using interactive mode
---
Fixes #1042
=> Misc QA fixes

packages/explorable-explanations/src/protectedAudience/index.ts, packages/extension/src/view/devtools/stateProviders/protectedAudience/protectedAudienceProvider.tsx
This PR aims to fix auction tab disappearance and fixes the auction tab flashing as well.
This PR fixes the following issues:
---
=> Fix: Auction tab data vanishing

packages/explorable-explanations/src/protectedAudience/index.ts, packages/explorable-explanations/src/protectedAudience/modules/auctions/index.ts, packages/explorable-explanations/src/protectedAudience/modules/flow.ts, packages/explorable-explanations/src/protectedAudience/modules/joinInterestGroup.ts, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseClickedInNonInteractiveModeCallback.ts, packages/explorable-explanations/src/protectedAudience/utils/mouseHandlers/mouseMovedInNonInteractiveMode.ts, packages/explorable-explanations/src/protectedAudience/utils/scrollToCircle.ts, packages/extension/src/serviceWorker/chromeListeners/onCommittedNavigationListener.ts, packages/extension/src/utils/sendMessageWrapper.ts, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/auctions/table/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/bids/receivedBidsTable.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/interestGroups/table.tsx
This PR aims to fix the following issues:
---
=> Misc patch fixes

extension.webpack.config.cjs
---
~~- [ ] This code is covered by unit tests to verify that it works as intended.~~
=> Fix automatic public path not being supported in Webpack config.

extension.webpack.config.cjs, packages/extension/src/contentScript/index.ts, packages/extension/src/contentScript/jsCookie.ts, packages/extension/src/manifest.json
This PR aims to split content script into functional parts.
- The PR splits the content script into 2 parts, one part will be used for frame overlay functionality another part is used to detect js cookies in all the frames.
- Verify that frameoverlay works as intended and JS cookie detection works as intended.
- This PR is a work to integrate some more functionality in the PSAT extension.
---
=> Refactor: Split content script into functional parts

.github/workflows/tests-cli-e2e-tests.yml, .github/workflows/tests-extension-e2e-tests.yml, packages/extension/src/view/devtools/app.tsx, packages/extension/src/view/devtools/e2e-tests/cookieLandingPage/knownBreakages.ts, packages/extension/src/view/devtools/e2e-tests/cookieTable/cookieFilter.ts, packages/extension/src/view/devtools/e2e-tests/cookieTable/cookieSorting.ts, packages/extension/src/view/devtools/e2e-tests/cookieTable/cookieTableFilterClearAllButton.ts, packages/extension/src/view/devtools/e2e-tests/rwsMembership/index.ts, packages/extension/src/view/devtools/test-utils/interaction.ts
This PR aims to fix failing e2e tests in PR #1071 
---
~~- [ ] The QA of this PR is done by a member of the QA team (to be checked by QA).~~ NA
=> Fix: Failing E2E tests

packages/extension/src/view/devtools/index.html
Rename leftover CAT reference to PSAT
---
- The QA of this PR is done by a member of the QA team (to be checked by QA).
Fixes #
=> Chore: Rename leftover CAT reference to PSAT

packages/design-system/src/components/cookieTable/utils/conditionalTableRowClassesHandler.ts, packages/design-system/src/components/table/components/index.tsx, packages/design-system/src/components/table/components/tableBody/bodyRow.tsx, packages/design-system/src/theme.css, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/interestGroups/table.tsx
Use lighter color for selected row
1. Pull and checkout the branch `fix/table-row-highlight`
2. Build and run the extension: `npm run build:all && npm run start`
4. Go to any table
5. Select a row
6. Make it lose focus by clicking outside the table
=> Fix: Table row highlight colors

packages/design-system/src/components/table/components/tableBody/bodyCell.tsx, packages/design-system/src/components/table/components/tableBody/bodyRow.tsx
FIxes html structure of the vertical bar in the the table
1. Pull and checkout the branch `fix/table-vertical-bar`
4. Go to PA EE, click the any intereset group bubble
5. Observer, there is a vertical bar next to the Event time and the data is displayed correctly
=> Fix: Table vertical bar

.github/workflows/tests-cli-e2e-tests.yml, .github/workflows/tests-extension-e2e-tests.yml
This PR aims to fix failing github actions
---
~~- [ ] The QA of this PR is done by a member of the QA team (to be checked by QA).~~ NA
=> Fix: GH actions

packages/extension/src/contentScript/prebid/prebidInterface.tsx, packages/extension/src/serviceWorker/chromeListeners/runtimeOnInstalledListener.ts, packages/extension/src/view/devtools/pages/constants.ts, packages/extension/src/view/devtools/pages/cookies/cookiesListing/useCookieListing/namePrefixIconSelector.tsx, packages/extension/src/view/devtools/pages/privacyProtection/ipProtection/mdlTable/legend.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/prebid/panel.tsx, packages/report/src/dashboard/components/utils/NamePrefixIconSelector.tsx
This PR fixes the issues raised by QA.
This PR fixes the following fixes:
---
=> Fix: Develop QA fixes

packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/auctions/components/adunitPanel/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/auctions/components/adunitPanel/panel.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/bids/panel.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/explorableExplanation/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/explorableExplanation/tableTabPanels/auctions/panel/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/explorableExplanation/tableTabPanels/bids/index.tsx
This PR 
- Creates a wrapper for the PA EE bids tabs panel to reuse tables
- Pass EE flag to distinguish UI in EE tabs.
---
Fixes #
=> Fix: Handle PA EE issues

packages/design-system/src/components/landingPage/LandingPage.tsx, packages/design-system/src/components/table/components/tableBody/bodyCell.tsx, packages/design-system/src/theme.css, packages/extension/src/serviceWorker/chromeListeners/onCommittedNavigationListener.ts, packages/extension/src/serviceWorker/chromeListeners/runtimeOnMessageListener.ts, packages/extension/src/serviceWorker/index.ts, packages/extension/src/utils/generateReportObject.ts, packages/extension/src/view/devtools/pages/privateAdvertising/topics/index.tsx
This PR fixes QA issues raised during release branch QA.
This PR fixes the following issues:
---
=> Fix: QA issues

packages/design-system/src/components/timeline/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/adUnits/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/auctions/components/adunitPanel/index.tsx, packages/extension/src/view/devtools/pages/privateAdvertising/protectedAudience/bids/index.tsx
This PR
- Fix the timeout text overlap issue in the timeline
- Default switching between Prebid / PAAPI 
---
Fixes #
=> Fix: Release Issues

packages/extension/src/view/devtools/pages/siteBoundaries/federatedCredential/explorableExplanation/components/sequenceDiagram.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/federatedCredential/explorableExplanation/components/timeline.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/federatedCredential/explorableExplanation/header.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/federatedCredential/explorableExplanation/panel.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/federatedCredential/explorableExplanation/tests/browser.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/federatedCredential/explorableExplanation/tests/index.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/federatedCredential/explorableExplanation/tests/panel.tsx, packages/extension/src/view/devtools/pages/siteBoundaries/federatedCredential/explorableExplanation/tests/timeline.tsx
This PR adds test cases for JSX components of FedCM EE.
---
- ~The QA of this PR is done by a member of the QA team (to be checked by QA).~
Fixes #
=> Chore: Add FedCM EE tests
